(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var B2=function(a){a.S("cardstatechange",g.YK(a)&&g.ZK(a)?1:0)},nsa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ak&&a.dataset){if(g.Oc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.jd("pollChoiceIndex"))},osa=function(a){return Math.pow(a,3)},psa=function(a){return 3*a*a-2*a*a*a},C2=function(a,b){var c=g.xo("use_default_events_client")?void 0:g.Qq;
(0,g.y)(b,function(d){d={csn:a,ve:g.Yr(d),eventType:4};var e={Wk:g.es(a),Yi:a};"UNDEFINED_CSN"==a?g.rs("visualElementShown",d,e):c?g.fq("visualElementShown",d,c,e):g.Rq("visualElementShown",d,e)})},D2=function(a,b){var c=g.xo("use_default_events_client")?void 0:g.Qq;
(0,g.y)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.Yr(d),eventType:e?16:8};e={Wk:g.es(a),Yi:a,AE:e};"UNDEFINED_CSN"==a?g.rs("visualElementHidden",d,e):c?g.fq("visualElementHidden",d,c,e):g.Rq("visualElementHidden",d,e)})},G2=function(a){a=g.Qa(a);
delete E2[a];g.Nb(E2)&&F2&&F2.stop()},rsa=function(){F2||(F2=new g.H(function(){qsa()},20));
var a=F2;a.isActive()||a.start()},qsa=function(){var a=(0,g.G)();
g.zb(E2,function(b){ssa(b,a)});
g.Nb(E2)||rsa()},H2=function(a,b,c,d){g.Gn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.G=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.F=0;this.B=null},ssa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;tsa(a,a.progress);1==a.progress?(a.o=0,G2(a),a.Gc(),a.lm()):a.eb()&&a.Ht()},tsa=function(a,b){g.Na(a.C)&&(b=a.C(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.G[c]-a.w[c])*b+a.w[c]},usa=function(a,b){g.Ke.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},I2=function(a,b,c,d,e){H2.call(this,b,c,d,e);
this.element=a},J2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
I2.call(this,a,b,c,d,e)},K2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},vsa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.Np(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},L2=function(a){return a.baseUrl||null},M2=function(a,b){return(0,g.ve)((0,g.Dc)(a,b,void 0),function(c){return!!c})},wsa=function(a,b,c){function d(Ab){var nb=Ab.hovercardButton;
if(!nb)return null;nb=nb.subscribeButtonRenderer;if(!nb)return null;var Zd=f(nb.unsubscribedButtonText),qf=f(nb.subscribedButtonText);if(nb.subscribed){var Mh=f(nb.subscriberCountWithUnsubscribeText);var Nh=f(nb.subscriberCountText)}else Mh=f(nb.subscriberCountText),Nh=f(nb.subscriberCountWithSubscribeText);var ag=null;return Ab.signinEndpoint&&(ag=g.Ib(Ab,"signinEndpoint","webNavigationEndpointData","url"),!ag)?null:Zd&&(qf||ag)?{subscribed:nb.subscribed,subscribeText:Zd,subscribeCount:Mh,unsubscribeText:qf,
unsubscribeCount:Nh,enabled:nb.enabled,signinUrl:ag,classic:Ab.useClassicSubscribeButton}:null}
function e(Ab){if(Ab){var nb=[],Zd=Ab.videoId;Zd&&nb.push("v="+Zd);(Zd=Ab.playlistId)&&nb.push("list="+Zd);(Ab=Ab.startTimeSeconds)&&nb.push("t="+Ab);return"/watch?"+nb.join("&")}}
function f(Ab){if(!Ab)return null;var nb=Ab.simpleText;return nb?nb:Ab.runs?(0,g.Dc)(Ab.runs,function(Zd){return Zd.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=null,t=null,u=null,z=null,C=!1,D=null,E=null,F=null,I=null,ia=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Ib(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;p="new";(C=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((F=g.Ib(l,"urlEndpoint","url"))&&(m=F),n=!0,p="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(ia=f(b.additionalFeesText)),(n=g.Ib(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Ib(b,"title","accessibility","accessibilityData","label");var pa=b.endpoint?b.endpoint.clickTrackingParams:null,sc="";if(b.metadata){var md=f(b.metadata);md&&(sc=md)}return{id:"element-"+c,type:k,title:f(b.title),metadata:sc,callToAction:f(b.callToAction),
Bw:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:E,isSubscribe:C,targetUrl:m,aG:n,Pb:{itct:pa},JO:p,Nk:a?a:null,eG:b.isPlaceholder,impressionUrls:M2(b.impressionUrls||[],L2),SF:M2(b.hovercardShowUrls||[],L2),clickUrls:M2(l.loggingUrls||[],L2),visualElement:g.Wr(b.trackingParams),productPrice:I,
additionalFeesText:ia}},N2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=M2(a.impressionUrls||[],L2);a.trackingParams&&(c.visualElement=g.Wr(a.trackingParams));c.elements=M2(a.elements||[],function(d,e){return wsa(b,d,e)});
return c},O2=function(a){g.vL.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.I=[];a=a.M();this.P=g.Ry(a)||g.Ty(a);this.L=!0;this.G=0;this.B=new g.Gr(this);g.B(this,this.B);this.B.K(this.player,g.nC("creatorendscreen"),this.QG);this.B.K(this.player,"crx_creatorendscreen",this.SG);this.B.K(this.player,"resize",this.Iy);this.B.K(window,"focus",this.GN);this.load();var b=g.pe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.He(this,function(){g.ue(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},xsa=function(a){return a.player.getVideoData().oc?"current":a.P?"new":"current"},P2=function(a){return"creator-endscreen-editor"===a.player.M().playerStyle},Q2=function(a,b,c){c=void 0===c?!0:c;
g.hR(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&ysa(a);c=[];d=new g.kC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.M().o||(a.w=new g.R({D:"div",H:"ytp-ce-shadow"}),g.iL(a.player,a.w.element,4),a.C=new g.lN(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=zsa(a,e);a.o[e.id]=f;a.F[e.id]=e;g.iL(a.player,f.element,4);var k=new g.kC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Asa(a,f,e)}g.eL(a.player,c);
a.Iy()}},ysa=function(a){var b=g.bs(),c=g.ds();
c&&b&&a.u.visualElement&&g.ys(c,b,a.u.visualElement)},zsa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",Y:["ytp-ce-element","ytp-ce-video"],O:{tabindex:"0","aria-label":b.Nk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-covering-image",O:R2(b)},{D:"div",H:"ytp-ce-covering-shadow-top"},{D:"a",H:"ytp-ce-covering-overlay",O:{href:S2(a,b.targetUrl),tabindex:"-1"},J:[{D:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Mn(b.title||"")},W:b.title},{D:"div",H:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.R(c);break;case "PLAYLIST":c={D:"div",Y:["ytp-ce-element","ytp-ce-playlist"],O:{tabindex:"0","aria-label":b.Nk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-covering-image",O:R2(b)},{D:"div",H:"ytp-ce-covering-shadow-top"},{D:"a",H:"ytp-ce-covering-overlay",O:{href:S2(a,b.targetUrl),tabindex:"-1"},J:[{D:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],O:{dir:g.Mn(b.title||"")},W:b.title},{D:"div",H:"ytp-ce-playlist-count",J:[{D:"div",
H:"ytp-ce-playlist-icon"},{D:"div",H:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.R(c);break;case "CHANNEL":c={D:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],O:{tabindex:"0","aria-label":b.Nk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-expanding-overlay",J:[{D:"div",H:"ytp-ce-expanding-overlay-hider"},{D:"div",H:"ytp-ce-expanding-overlay-background"},{D:"div",H:"ytp-ce-expanding-overlay-content",
J:[{D:"div",H:"ytp-ce-expanding-overlay-body",J:[{D:"div",H:"ytp-ce-expanding-overlay-body-padding",J:[{D:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],O:{href:S2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Mn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",H:"ytp-ce-subscribe-container",J:[{D:"div",H:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",H:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",H:"ytp-ce-expanding-image",O:R2(b)}]};c=new g.R(c);var d=g.be(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.J(d,"ytp-ce-subscribe-button");if(a.player.M().o){var e=null;var f=b.Pb.itct}else e="endscreen",f=null;e=new g.AQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={D:"div",Y:["ytp-ce-element","ytp-ce-website"],O:{tabindex:"0","aria-label":b.Nk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-expanding-overlay",J:[{D:"div",H:"ytp-ce-expanding-overlay-hider"},{D:"div",H:"ytp-ce-expanding-overlay-background"},{D:"div",H:"ytp-ce-expanding-overlay-content",J:[{D:"div",H:"ytp-ce-expanding-overlay-body",
J:[{D:"div",H:"ytp-ce-expanding-overlay-body-padding",J:[{D:"div",H:"ytp-ce-website-title",O:{dir:g.Mn(b.title||"")},W:b.title},{D:"div",H:"ytp-ce-website-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],O:{href:S2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",H:"ytp-ce-expanding-image",O:R2(b)},{D:"div",H:"ytp-ce-expanding-icon",O:Bsa(b.iconUrl)}]};c=new g.R(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",H:"ytp-ce-merchandise-price-container",
J:[{D:"div",H:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.J.push({D:"div",H:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],O:{tabindex:"0","aria-label":b.Nk||"","aria-hidden":"true"},J:[{D:"div",H:"ytp-ce-element-shadow"},{D:"div",H:"ytp-ce-expanding-overlay",J:[{D:"div",H:"ytp-ce-expanding-overlay-hider"},{D:"div",H:"ytp-ce-expanding-overlay-background"},{D:"div",H:"ytp-ce-expanding-overlay-content",J:[{D:"div",
H:"ytp-ce-expanding-overlay-body",J:[{D:"div",H:"ytp-ce-expanding-overlay-body-padding",J:[{D:"div",H:"ytp-ce-merchandise-title",O:{dir:g.Mn(b.title||"")},W:b.title},c,{D:"div",H:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],O:{href:S2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",H:"ytp-ce-expanding-image",O:R2(b)},{D:"div",H:"ytp-ce-merchandise-invideo-cta-container",J:[{D:"div",H:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.R(c)}b.eG&&g.J(c.element,"ytp-ce-placeholder");return c},R2=function(a){if(a.Bw)var b=a.Bw.thumbnails;
return Bsa(b?b[b.length-1].url:null)},Bsa=function(a){return a?{style:"background-image: url("+a+")"}:{}},Asa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ka("mouseenter",(0,g.x)(a.Ns,a,b,c));b.ka("mouseleave",(0,g.x)(a.Mt,a,b,c));a.player.M().o||b.ka("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ka("click",(0,g.x)(a.nA,a,c));b.ka("keypress",(0,g.x)(a.nA,a,c));b.ka("focus",(0,g.x)(function(l,m){this.Ns(l,m)},a,b,c));
b.ka("blur",(0,g.x)(function(l,m){this.Mt(l,m)},a,b,c));
b.ka("touchstart",(0,g.x)(a.Ns,a,b,c));var f=g.de("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.En(b.element,"ytp-ce-element-hover");g.En(b.element,"ytp-ce-force-expand")});
b.ka("keydown",(0,g.x)(function(l,m){this.L=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.J(l.element,"ytp-ce-force-expand"),T2(this,m.id,!0)):(g.En(l.element,"ytp-ce-force-expand"),g.En(l.element,"ytp-ce-element-hover"),T2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ka("blur",g.Ra(function(){"none"!=m.style.display&&a.L&&m.focus()})),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
c(g.de("ytp-sb-subscribe",b.element));c(g.de("ytp-sb-unsubscribe",b.element));b.ka("focus",d);b.ka("blur",e)},S2=function(a,b){var c=a.player.M();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.tz(c)+b}else return"";return b},T2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.K(a.o[d].element,"ytp-ce-element-shadow-show",c)},U2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||P2(a))c&&c();else{b=Csa(a,b);var e=0,f=!1,k=new g.H(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.cr(b[a],d)}},V2=function(a,b,c){U2(a,b.clickUrls,c);
(a=g.ds())&&b.aG&&g.zs(a,b.visualElement)},Csa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Dsa(b[e],c));return d},Dsa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Esa=function(a){return g.La(a)&&a.length?a[0]:a},W2=function(a){return"string"===typeof a?a:""},X2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Gsa=function(a){var b=Fsa;
if(null==a)return null;if(g.Ma(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Hsa=function(a){this.externalId=a},Isa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},Y2=function(a){if(!a)return null;
var b=g.xc(W2(a.value));b=g.vc(b);if(!b)return null;var c=X2(a.target,Jsa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Isa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Z2=function(a){return a.value?a.value:null},Ksa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Fsa=function(a){if(!a)return null;
var b=X2(a.type,Lsa),c=X2(a.trigger,Msa),d=Esa(a.url);d=Y2(d?d:null);a=Esa(a.subscribeData);var e=a?a:null;e?(a=W2(e.external_user_id),e=W2(e.subscription_token),a=a&&e?new Hsa(a):null):a=null;return b?new Ksa(b,c,d,a):null},$2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Nsa=function(a,b){return g.Ya(a.o,b,void 0)},Osa=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Psa=function(a,b){this.merchant=a;
this.price=b},Qsa=function(a){this.o=a},Rsa=function(a,b,c){b&&(c?a3(a,(0,g.Dc)(b,g.Ra(function(d,e){return g.en(e,d)},c))):a3(a,b))},a3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.cr(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Ssa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.A=c;this.videoData=d;this.logger=e;this.N=f;this.u=k},b3=function(a,b){this.o=a;
this.w=b},Vsa=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Tsa(b,k))},a);
var d={D:"ul",O:{role:"radiogroup"},J:c},e={};b.bj&&(e["aria-label"]=g.gM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",H:"iv-card-content",J:[c3("h2",e,b.title),{D:"form",J:[{D:"fieldset",J:[d]}]}]}];b.bj&&(f.push("iv-card-unavailable"),d.push({D:"div",Y:["iv-card-sign-in"],J:[{D:"h2",W:"Want to vote?"},{D:"a",Y:["iv-card-sign-in-button","iv-button"],O:{href:Z2(b.bj)},J:[{D:"span",Y:["iv-button-content"],W:"Sign in"}]}]}));f=new g.R({D:"div",
Y:f,J:d});d=f.element;Usa(b,d);vsa(a.o.o,d,g.Ra(a.A,b),a);(0,g.y)(g.ce("iv-card-poll-choice-input",d),function(k){this.o.o.ka(k,"focus",g.Ra(this.u,!0));this.o.o.ka(k,"blur",g.Ra(this.u,!1))},a);
b.bj&&(d=g.de("iv-card-sign-in-button",d),a.w(d,b.bj,b.id,b.Pb,b.Hc.click,5));return f},Wsa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.cP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.dG&&b.Vv?{D:"span",Y:d,O:e,W:b.Vv}:"";c={D:"div",Y:["iv-card",c],J:[{D:"a",H:"iv-click-target",O:{href:Z2(b.url)},J:[d3(b.gj,d?{D:"div",H:"iv-card-image-text",J:[d,b.priceText]}:""),{D:"div",H:"iv-card-content",J:[{D:"h2",H:"iv-card-primary-link",W:b.title},e3(a,b)]}]}]};c=new g.R(c);f3(a,g.ce("iv-click-target",c.element),b,b.url);return c},g3=function(a){return a.customMessage?
c3("div","iv-card-message",a.customMessage):""},d3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",H:"iv-card-image",O:{style:c},J:d}},e3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(c3("li","",d))},a);
return{D:"ul",H:"iv-card-meta-info",J:c}},Tsa=function(a,b){return{D:"li",
H:Osa(a,b.index),J:[{D:"label",J:[{D:"input",H:"iv-card-poll-choice-input",O:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",H:"iv-card-poll-choice-text",J:[{D:"span",H:"iv-card-poll-choice-percent"},c3("span",void 0,b.desc)]}]},{D:"div",H:"iv-card-poll-result",J:[{D:"div",H:"iv-card-poll-result-bar"}]}]}},c3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.La(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.Mn(c);return{D:a,O:b,W:c}},Xsa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.mn&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.mn+");");c.dir=g.Mn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",H:"iv-card-link-icon"}));return{D:"div",Y:b,O:c,J:d}},Usa=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.de(Osa(a,e.index),b);e=e.count/c;null==a.Ce&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Ce==d);f.getElementsByTagName("input")[0].checked=a.Ce==d;var k=Math.floor(100*e).toFixed(0),l=g.de("iv-card-poll-choice-percent",f);g.ze(l,g.gM("$PERCENT%",{PERCENT:k}));f=g.de("iv-card-poll-result-bar",f);g.th(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.Ce);g.K(b,"iv-card-poll-expanded",
null!=a.Ce&&1<a.choices.length)},f3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Pb,c.Hc.click,5)},a)},Ysa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Zsa=function(a,b){return b?b:Ysa(a)?"current":"new"},h3=function(a,b){g.A.call(this);
var c=this;this.Ka=a;this.context=b;this.Ou=!1;this.ga=new Map;this.ma=new Map;this.context.N.addEventListener(g.nC("annotations_module"),function(d){(d=c.ga.get(d))&&d.apply(c)});
this.context.N.addEventListener("crx_annotations_module",function(d){(d=c.ma.get(d))&&d.apply(c)})},$sa=function(a,b,c,d,e){var f=Z2(b);
if(f){var k=Zsa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.N.pauseVideo();var m=this.context.videoData.oc||!1,n=g.mq(f||"");m&&n&&(n.v||n.list)?g.tT(this.context.N.app,n.v,c,n.list,!1,void 0):g.GN(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);a3(a.context.logger,d,l,e);Ysa(f)||(a=g.ds(),d=c.itct,a&&d&&g.zs(a,g.Wr(d)))}},ata=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},i3=function(a,b,c){return{Kx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
gC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Up:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},l3=function(a,b,c){h3.call(this,b,c);
var d=this;this.u=a;this.aa=this.Ia=this.B=this.Ea=!1;this.ha=null;this.ca=new g.H(g.Ia,c.A.Wa?4E3:3E3);g.B(this,this.ca);this.za=new g.H(g.Ia);g.B(this,this.za);this.G=new b3(c,(0,g.x)(this.vk,this),(0,g.x)(this.Ao,this));this.T=new g.R({D:"div",H:"iv-drawer",O:{id:"iv-drawer"},J:[{D:"div",H:"iv-drawer-header",O:{"aria-role":"heading"},J:[{D:"span",H:"iv-drawer-header-text"},{D:"button",Y:["iv-drawer-close-button","ytp-button"],O:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",H:"iv-drawer-content"}]});
g.B(this,this.T);this.C=this.T.element;this.oa=new g.lN(this.T,330);g.B(this,this.oa);this.Ca=g.de("iv-drawer-header-text",this.C);this.A=g.de("iv-drawer-content",this.C);this.w=[];this.Aa=this.R=this.F=this.da=this.o=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ia&&j3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ia=d.B)&&k3(d)});
this.L=this.I=this.Z=null;this.P=0},bta=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){j3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){k3(a)});
var c=b.data.headerText;g.ze(a.Ca,c);a.R&&a.R.setAttribute("title",c);a.Z=g.Wr(b.data.trackingParams);a.L=g.Wr(b.data.closeTrackingParams);a.I=g.Wr(b.data.iconTrackingParams)},cta=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.P;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"simple",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Pb:m3(a,c,b,d),sponsored:!1,Hc:i3(d,e,d.command),de:d.trackingParams?g.Wr(d.trackingParams):null,Yd:e.trackingParams?
g.Wr(e.trackingParams):null,yd:f&&f.trackingParams?g.Wr(f.trackingParams):null,imageUrl:n3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.T(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,mn:null,title:d.title?g.T(d.title):"",customMessage:d.callToAction?g.T(d.callToAction):"",url:d.command.urlEndpoint.url?Y2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};o3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"collaborator",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Pb:m3(a,c,b,d),sponsored:!1,Hc:i3(d,e,d.endpoint),de:d.trackingParams?g.Wr(d.trackingParams):null,Yd:e.trackingParams?g.Wr(e.trackingParams):null,yd:f&&f.trackingParams?
g.Wr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.T(d.customText):null,nB:n3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.T(d.channelName):"",metaInfo:[d.subscriberCountText?g.T(d.subscriberCountText):""],url:Y2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};o3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"playlist",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Pb:m3(a,c,b,d),sponsored:!1,Hc:i3(d,e,d.action),de:d.trackingParams?g.Wr(d.trackingParams):null,Yd:e.trackingParams?g.Wr(e.trackingParams):null,yd:f&&f.trackingParams?g.Wr(f.trackingParams):
null,gj:n3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.T(d.customMessage):null,playlistVideoCount:g.T(d.playlistVideoCount),title:d.playlistTitle?g.T(d.playlistTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.videoCountText?g.T(d.videoCountText):""],url:Y2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:ata(d.action)})};o3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"video",teaserText:g.T(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Pb:m3(a,c,b,d),sponsored:!1,Hc:i3(d,e,d.action),de:d.trackingParams?g.Wr(d.trackingParams):null,Yd:e.trackingParams?g.Wr(e.trackingParams):null,yd:f&&f.trackingParams?g.Wr(f.trackingParams):null,gj:n3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.T(d.lengthString):null,customMessage:d.customMessage?g.T(d.customMessage):null,title:d.videoTitle?g.T(d.videoTitle):"",metaInfo:[d.channelName?g.T(d.channelName):"",d.viewCountText?g.T(d.viewCountText):""],isLiveNow:!!d.badge,url:Y2({pause_on_navigation:!a.context.videoData.ua,target:"new",value:ata(d.action)})};o3(a,c)}a.P++},n3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},m3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},eta=function(a,b){var c=dta(a,b);
c&&(c==a.o&&(a.o=null),a.u.removeCueRange(c.card.id),g.ue(c.Sq),g.eb(a.w,c),a.pn(),p3(a))},j3=function(a,b,c){if(!a.B){a.oa.show();
a.da=new g.H(function(){g.J(a.context.N.getRootNode(),g.lM.IV_DRAWER_OPEN)},0);
a.da.start();a.ha=g.Ep(a.A,"mousewheel",(0,g.x)(a.KL,a));a.B=!0;var d=g.ds();d&&a.Z&&a.L&&C2(d,[a.Z,a.L]);var e={TRIGGER_TYPE:b};(0,g.y)(a.w,function(f){f.my||(f.my=!0,Rsa(a.context.logger,f.card.Hc.Kx,e));d&&C2(d,[f.card.de])});
B2(a.u);c&&(a.F=new g.H(function(){a.va=a.R;a.Aa.focus()},330),a.F.start())}},k3=function(a){a.B&&(a.oa.hide(),g.Fp(a.ha),a.ha=null,g.En(a.context.N.getRootNode(),g.lM.IV_DRAWER_OPEN),a.B=!1,B2(a.u),a.F&&a.F.stop(),a.F=new g.H(function(){a.va&&(a.va.focus(),a.va=null)},330),a.F.start())},fta=function(a){var b=g.de("iv-drawer-close-button",a.C);
a.context.o.ka(b,"click",a.gE,a);a.context.o.ka(a.A,"touchend",function(){a.ca.start()});
a.context.o.ka(a.A,"scroll",a.wE,a);a.context.u.subscribe("onHideControls",function(){a.aa=!0});
a.context.u.subscribe("onShowControls",function(){a.aa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.aa=g.Cn(a.u.getRootNode(),"ytp-autohide")});
a.V.push(g.Oo("iv-button-shown",a.mG,a));a.V.push(g.Oo("iv-button-hidden",a.lG,a));a.V.push(g.Oo("iv-teaser-shown",a.pG,a));a.V.push(g.Oo("iv-teaser-hidden",a.oG,a));a.V.push(g.Oo("iv-teaser-clicked",a.nG,a))},o3=function(a,b){a.Ea||(g.Dn(a.sa(),[g.lM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.iL(a.u,a.C,5),fta(a),a.R=g.de("ytp-cards-button",a.u.getRootNode()),a.Aa=g.de("iv-drawer-close-button",a.C),a.Ea=!0);eta(a,b.id);var c=gta(a,b);if(c){var d={card:b,Sq:c.element,my:!1},e=hta(a,d);g.lb(a.w,e,0,d);c.ba(a.A,e);a.pn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ra(a.tO,d)):(c=1E3*a.context.N.getCurrentTime(),5E3>c&&c>b.startMs&&a.SB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ra(a.SB,d)),p3(a))}},gta=function(a,b){switch(b.type){case "simple":var c=
a.G;
var d=b.displayDomain?{D:"div",H:"iv-card-image-text",W:b.displayDomain}:"";var e=Xsa(b);d={D:"div",Y:["iv-card"],J:[{D:"a",H:"iv-click-target",O:{href:Z2(b.url)},J:[d3(b.imageUrl,d),{D:"div",H:"iv-card-content",J:[c3("h2",void 0,b.title),e]}]}]};d=new g.R(d);f3(c,g.ce("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.G,d={D:"div",Y:["iv-card","iv-card-channel"],J:[{D:"a",Y:["iv-click-target"],O:{href:Z2(b.url),"data-ytid":b.channelId},J:[d3(b.nB),{D:"div",H:"iv-card-content",
J:[g3(b),{D:"h2",H:"iv-card-primary-link",W:b.title},e3(c,b)]}]}]},d=new g.R(d),f3(c,g.ce("iv-click-target",d.element),b,b.url),d;case "episode":return Wsa(a.G,b,"iv-card-episode");case "movie":return Wsa(a.G,b,"iv-card-movie");case "playlist":return c=a.G,d={D:"div",Y:["iv-card","iv-card-playlist"],J:[{D:"a",H:"iv-click-target",O:{href:Z2(b.url)},J:[d3(b.gj,{D:"div",H:"iv-card-image-overlay",J:[{D:"span",H:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",H:"iv-card-content",J:[g3(b),
c3("h2","iv-card-primary-link",b.title),e3(c,b)]}]}]},d=new g.R(d),f3(c,g.ce("iv-click-target",d.element),b,b.url),d;case "poll":return Vsa(a.G,b);case "productListing":c=a.G;var f=!g.bb(b.offers);d=["iv-card"];e="";var k=Xsa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",H:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",H:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",J:k});d={D:"div",Y:d,O:{tabindex:"0"},J:[{D:"a",
Y:["iv-card-image","iv-click-target"],O:{style:"background-image: url("+b.imageUrl+");",href:Z2(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",H:"iv-card-content",J:[b.sponsored?{D:"div",H:"iv-card-sponsored",J:["Sponsored",{D:"div",H:"iv-ad-info-container",J:[{D:"div",H:"iv-ad-info",W:"{{adInfo}}"},{D:"div",H:"iv-ad-info-icon-container",J:[{D:"div",H:"iv-ad-info-icon"},{D:"div",H:"iv-ad-info-callout"}]}]}]}:"",{D:"a",H:"iv-click-target",O:{href:Z2(b.url)},J:[c3("h2",e,b.title),k]}]}]};d=new g.R(d);
e=g.pe("span");g.ze(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.qb(e,"adInfo");f3(c,g.ce("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.G,d=b.isLiveNow?{D:"span",Y:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",Y:["iv-card","iv-card-video"],J:[{D:"a",H:"iv-click-target",O:{href:Z2(b.url)},J:[d3(b.gj,b.videoDuration?{D:"span",H:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",H:"iv-card-content",
J:[g3(b),c3("h2","iv-card-primary-link",b.title),e3(c,b),d]}]}]},d=new g.R(d),f3(c,g.ce("iv-click-target",d.element),b,b.url),d}return null},hta=function(a,b){if(0==a.w.length)return 0;
var c=g.Za(a.w,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},ita=function(a){return a.o?"productListing"==a.o.card.type:(0,g.ui)(a.w,function(b){return"productListing"==b.card.type})},p3=function(a){g.K(a.u.getRootNode(),"ytp-cards-shopping-active",ita(a))},jta=function(a,b){if(a.T.Ha()){var c=new H2([0,
a.A.scrollTop],[0,b.Sq.offsetTop],600,psa);a.context.w.ka(c,"animate",function(d){a.A.scrollTop=d.y});
a.context.w.ka(c,"finish",function(d){a.A.scrollTop=d.y});
c.play()}else g.Qu(a.T,!0),a.A.scrollTop=b.Sq.offsetTop,g.Qu(a.T,!1)},q3=function(a){return a.o&&a.o.card?a.o.card:a.w[0]&&a.w[0].card?a.w[0].card:null},dta=function(a,b){return g.Ya(a.w,function(c){return c.card.id==b})},r3=function(a,b,c){h3.call(this,a,b);
this.annotation=c;this.isActive=!1},kta=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},s3=function(a,b,c){r3.call(this,a,b,c);
this.u=null;this.F=!1;this.w=null;this.A=!1;this.o=this.C=this.B=null},t3=function(a,b,c){r3.call(this,a,b,c);
this.I=this.B=this.P=!1;this.F=5E3;this.A=null;this.G=g.oe("DIV","iv-promo-contents");this.u=this.w=this.o=null;this.C=new g.H(function(){this.o.setAttribute("aria-hidden",!0);g.Ph(this.w,!1);g.Ph(this.u,!0)},700,this);
g.B(this,this.C)},lta=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.F=b.collapse_delay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.sa().setAttribute("aria-hidden",!0);a.sa().setAttribute("aria-label","Promotion");a.sa().tabIndex=0;var e=a.annotation.kc(),f=b.image_url;if(f){var k=g.oe("DIV",["iv-promo-img","iv-click-target"]);f=g.oe("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.oe("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.oe("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.vk(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.oe("A","iv-promo-txt"),g.Yc(f,Z2(e)),a.o=f):a.o=g.oe("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.oe("P",null,g.oe("STRONG",null,b.text_line_1));var m=g.oe("P",null,g.oe("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.P(a.context.A.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.oe("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.oe("BUTTON",["iv-button","iv-promo-button"],g.oe("SPAN","iv-button-content",f));var p=g.oe("DIV","iv-promo-button-container");p.appendChild(f);e&&a.vk(a.sa(),e,a.annotation.id,b.session_data,void 0,c)}g.J(a.o,"iv-click-target");e&&a.vk(a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.oe("P",
null,g.oe("SPAN",null,b.text_line_1)),m=g.oe("P",null,g.oe("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.oe("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.o,"iv-click-target"),e&&a.vk(a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.G.appendChild(a.o);p&&a.G.appendChild(p);c=g.oe("DIV","iv-promo-actions");a.u=g.oe("BUTTON",["iv-promo-expand","ytp-button"]);a.u.title="Expand";a.context.o.ka(a.u,"click",g.Ra(a.Sr,
5E3),a);c.appendChild(a.u);g.Ph(a.u,!1);a.context.o.ka(a.sa(),"mouseover",a.vF,a);a.context.o.ka(a.sa(),"mouseout",a.uF,a);a.context.o.ka(a.sa(),"touchend",g.Ra(a.Sr,5E3),a);a.w=g.oe("BUTTON",["iv-promo-close","ytp-button"]);a.w.title="Close";a.context.o.ka(a.w,"click","cta"==a.annotation.style&&b.text_line_3?a.nF:a.mF,a);c.appendChild(a.w);g.Dn(a.sa(),d);k&&(a.sa().appendChild(k),n&&k.appendChild(n));a.sa().appendChild(a.G);a.sa().appendChild(c)},mta=function(a){a.B||a.I||a.A||(g.J(a.sa(),"iv-promo-collapsed"),
a.B=!0,a.C.start())},nta=function(a){a.C.stop();
a.B&&(g.Fn(a.sa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.B=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Ph(a.u,!1),g.Ph(a.w,!0))},ota=function(a,b){a.A||(a.A=g.Vf(function(){u3(this);
mta(this)},b,a))},u3=function(a){a.A&&(g.v.clearTimeout(a.A),a.A=null)},v3=function(a){g.vL.call(this,a);
this.P=!1;this.I=0;this.F={};this.V=new Qsa(a);this.B=new g.Gr(this);g.B(this,this.B);this.C=this.w=null;this.B.K(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.B.K(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.B.K(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.B.K(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.B.K(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.iM,this);this.subscribe("resize",this.np,this);this.player.M().I.subscribe("vast_info_card_add",this.ZA,this);this.T=new g.Gr(this);g.B(this,this.T);this.R=g.oe("DIV","video-custom-annotations");this.u=new g.R({D:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.B(this,this.u);g.iL(this.player,this.u.element,4);this.u.hide();this.A=new g.R({D:"div",Y:["ytp-iv-video-content"]});g.B(this,this.A);g.re(this.A.element,g.oe("DIV","video-annotations",
this.R));this.G=this.o=null;this.L=[];pta(this)&&this.load();var b=g.pe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.He(this,function(){g.ue(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},qta=function(){var a=g.oe("DIV",["annotation",
"annotation-type-custom"]);g.Ph(a,!1);return a},rta=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},pta=function(a){var b=a.player.M();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.IC||b.I.get(a.videoId)||g.KB(a)||g.LB(a)?!0:!1},sta=function(a,b,c){a.P=!0;
a.C=g.Eq(b,c)},tta=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(tta(a,e))}return c},uta=function(a,b,c){return!(a.loaded&&a.I==b&&a.player.getVideoData().videoId==
c)},xta=function(a){var b=a.player.getVideoData();
if(b.be){var c=a.player.M().I.get(b.videoId);if(c){var d={format:"XML",Zd:{},method:"POST",withCredentials:!0};d.Gc=(0,g.x)(function(e,f,k){uta(this,e,f)||(e=g.yq(k)&&k.responseXML?k.responseXML:null)&&w3(this,e)},a,a.I,b.videoId);
g.Vp()&&(d.Gc=vta(a,d.Gc));d.sb={ic_only:"1"};wta(d,c);a.P=!0;g.Eq(b.be,d)}}},wta=function(a,b){a.method="POST";
a.sb=a.sb||{};b.un&&(a.sb.ic_coll=b.un);b.vn&&(a.sb.ic_xml=b.vn);b.Lm&&(a.sb.ic_track=b.Lm)},yta=function(a){var b=new g.R({D:"div"});
g.Ph(b.element,!1);var c=new l3(a.player,b.element,x3(a));g.B(c,b);b.ba(a.u.element);c.Am();return c},x3=function(a){if(!a.G){var b=new K2(a);
g.B(a,b);var c=new g.D1(a);g.B(a,c);a.G=new Ssa(b,c,a.player.M(),a.player.getVideoData(),a.V,a.player,a.Kh)}return a.G},w3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ds();if(e){var f=g.bs();f&&g.ts(g.xo("use_default_events_client")?void 0:g.Qq,e,f,[g.Wr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=tta(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=X2(k.type,zta),t=X2(k.style,Ata),u=W2(k.data),z=0!=u.length?JSON.parse(u):{},C=Gsa(k.action);f=n&&p?new $2(n,p,t,C,z):null}else f=null}catch(ia){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var D=qta(),E=null;switch(m.type){case "branding":if(k.player.M().Ca)break;k.u.element.appendChild(D);E=new s3(D,x3(k),m);break;case "promotion":g.iL(k.player,D,4),E=new t3(D,x3(k),m)}E&&E.Am();if(k=E)g.B(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=yta(a),g.B(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Kx:k.impression,click:k.click,close:k.close,gC:k.teaser_impression,Up:k.teaser_click},m=
f.data.tracking_params||{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Pb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Hc:k,de:m.card?g.Wr(m.card):null,Yd:m.teaser?g.Wr(m.teaser):null,yd:m.icon?g.Wr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,nB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:Y2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Pb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Hc:k,de:m.card?g.Wr(m.card):null,Yd:m.teaser?g.Wr(m.teaser):null,
yd:m.icon?g.Wr(m.icon):null,gj:f.data.image_url,Vv:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,dG:!!f.data.is_paygated,cP:!!f.data.user_has_entitlement,url:Y2({target:f.data.target||"new",value:f.data.url})};o3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Pb:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Hc:k,de:m.card?g.Wr(m.card):null,Yd:m.teaser?g.Wr(m.teaser):null,yd:m.icon?g.Wr(m.icon):null,gj:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:Y2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Pb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Hc:k,de:m.card?g.Wr(m.card):null,Yd:m.teaser?g.Wr(m.teaser):null,yd:m.icon?g.Wr(m.icon):null,title:f.data.title,choices:f.data.choices,Ce:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,bj:f.data.signin_url?Y2({target:"current",value:f.data.signin_url}):null,nP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};o3(c,f);break;case "productListing":f.data.signin_url&&
(D=Y2({target:"current",value:f.data.signin_url}));E=[];for(var F=f.data.offers||[],I=0;I<F.length;I++)E.push(new Psa(g.fd(F[I].merchant),g.fd(F[I].price)));f={tT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Pb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Hc:k,de:m.card?g.Wr(m.card):null,Yd:m.teaser?g.Wr(m.teaser):null,yd:m.icon?g.Wr(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,mn:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:Y2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),bj:D,QT:f.data.signin_title?f.data.signin_title:null,PT:f.data.signin_message?f.data.signin_message:null,offers:E};o3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Pb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Hc:k,de:m.card?g.Wr(m.card):null,Yd:m.teaser?g.Wr(m.teaser):null,yd:m.icon?g.Wr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,mn:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:Y2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};o3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Pb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Hc:k,de:m.card?g.Wr(m.card):null,Yd:m.teaser?
g.Wr(m.teaser):null,yd:m.icon?g.Wr(m.icon):null,gj:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:Y2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},o3(c,f)}}else bta(a.o,f);c=!0}}}c&&(B2(a.player),a.np())},Bta=function(a,b){var c=!1;
a.o||(a.o=yta(a),g.B(a,a.o));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())cta(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.T(b.headerText):"",g.ze(c.Ca,d),c.R&&c.R.setAttribute("title",d),c.Z=b.trackingParams?g.Wr(b.trackingParams):null,c.L=b.closeButton.infoCardIconRenderer.trackingParams?g.Wr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.I=b.icon.infoCardIconRenderer.trackingParams?g.Wr(b.icon.infoCardIconRenderer.trackingParams):null,B2(a.player),a.np())},Cta=
function(a,b,c,d,e){if(!a.player.M().Ca){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Ksa("openUrl","click",new Isa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.T(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.T(b.subscriberCountText))):(b.subscriberCountText&&(e=g.T(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.T(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.T(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.T(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new $2(c,"branding","branding",f,d);d=qta();a.u.element.appendChild(d);f=new s3(d,x3(a),f);f.Am();g.B(f,f);a.F[c]=f}},vta=function(a,b){return(0,g.x)(function(){if(!this.ea()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.L.push(g.Tp(b))}},a)},E2={},F2=null;g.Ta(H2,g.Gn);g.h=H2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(this.eb())return!1;G2(this);this.startTime=a=(0,g.G)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.lp();this.re("play");-1==this.o&&this.re("resume");this.o=1;var b=g.Qa(this);b in E2||(E2[b]=this);rsa();ssa(this,a);return!0};
g.h.stop=function(a){G2(this);this.o=0;a&&(this.progress=1);tsa(this,this.progress);this.re("stop");this.lm()};
g.h.pause=function(){this.eb()&&(G2(this),this.o=-1,this.re("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.re("destroy");H2.Gb.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Ht=function(){this.re("animate")};
g.h.re=function(a){this.dispatchEvent(new usa(a,this))};
g.Ta(usa,g.Ke);g.Ta(I2,H2);I2.prototype.A=g.Ia;I2.prototype.Ht=function(){this.A();I2.Gb.Ht.call(this)};
I2.prototype.lm=function(){this.A();I2.Gb.lm.call(this)};
I2.prototype.lp=function(){this.A();I2.Gb.lp.call(this)};
g.Ta(J2,I2);J2.prototype.A=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(K2,g.A);K2.prototype.ka=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Ep(a,b,c);this.o.push(a);return a};
K2.prototype.Ds=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Op(a,b,c);this.o.push(a);return a};
K2.prototype.bb=function(a){g.Fp(a);g.eb(this.o,a)};
K2.prototype.X=function(){g.Fp(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.r(O2,g.vL);g.h=O2.prototype;g.h.load=function(){g.vL.prototype.load.call(this);if(!P2(this)){var a=g.JB(this.player.getVideoData());if(a)a=N2(a,xsa(this)),Q2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",Gc:(0,g.x)(this.UK,this,a),Zd:{v:a},withCredentials:!0};this.P&&(a.Zd.ptype="embedded");var c=this.player.getVideoData().Hn;c&&(a.sb={ad_tracking:c});if(b=g.IB(b))if(b=g.xc(b),b=g.vc(b))this.A=g.Eq(b,a)}}};
g.h.unload=function(){Q2(this,null);this.A&&(this.A.abort(),this.A=null);g.vL.prototype.unload.call(this)};
g.h.Pc=function(a,b){if(!P2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=N2(b,"new");Q2(this,c);return!0}return null};
g.h.getOptions=function(){return P2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.UK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=N2(c,xsa(this)))}Q2(this,c)};
g.h.Iy=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Dta.length;f++){var k=Math.abs(b.width-Dta[f]);if(-1==e||d>=k)e=f,d=k}d=Eta[e];this.w&&g.th(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Lh(e.element,Math.round(k.width*a.width),f);g.Bh(e.element,m,n);g.Fn(e.element,Fta);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Fn(e.element,Eta);g.J(e.element,d);(e=g.be(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.th(e,"height",f+"px")}}}}};
g.h.QG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())U2(this,this.u.impressionUrls),(a=g.ds())&&this.u.visualElement&&g.us(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");U2(this,c.impressionUrls);(b=g.ds())&&g.us(b,c.visualElement);this.player.M().w&&this.player.na("endscreenelementshown",a)}};
g.h.SG=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.En(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.En(b,"ytp-ce-shown");this.player.M().w&&this.player.na("endscreenelementhidden",a)}};
g.h.GN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Fn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.nA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Cn(c,"ytp-ce-element");){g.Cn(c,"subscribe-label")&&V2(this,a);if(g.Cn(c,"ytp-ce-channel-subscribe"))return;c=g.xe(c)}if(!c||g.Cn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Mt(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.JO?(V2(this,a),this.RB(),this.player.pauseVideo(),c=g.xc(S2(this,a.targetUrl)),c=g.vc(c),g.GN(c,void 0,a.Pb)):(c=this.player.getVideoData().oc,
c=(0,g.x)(this.BO,this,c,S2(this,a.targetUrl),a.Pb),c=(0,g.x)(this.RB,this,c),V2(this,a,c))}}};
g.h.BO=function(a,b,c){var d=g.mq(b);a&&d&&(d.v||d.list)?g.tT(this.player.app,d.v,c,d.list,!1,void 0):g.FN(b,c)};
g.h.Ns=function(a,b){g.Cn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):this.player.M().o?(new g.H(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),U2(this,b.SF),T2(this,b.id,!0))};
g.h.Mt=function(a,b){g.En(a.element,"ytp-ce-element-hover");g.En(a.element,"ytp-ce-force-expand");T2(this,b.id,!1)};
g.h.RB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Dta=[346,426,470,506,570,640,853,1280,1920],Eta="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Fta=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Jsa={sQ:"current",QR:"new"};var Lsa={CLOSE:"close",TR:"openUrl",DD:"subscribe"},Msa={mQ:"click",CLOSE:"close",gR:"hidden",zS:"rollOut",AS:"rollOver",DS:"shown"};$2.prototype.kc=function(){var a=Nsa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var Ata={PP:"anchored",YC:"branding",CHANNEL:"channel",rQ:"cta",iR:"highlightText",zR:"label",PLAYLIST:"playlist",lS:"popup",HS:"speech",DD:"subscribe",RS:"title",VIDEO:"video",fT:"website"},zta={YC:"branding",dQ:"card",zQ:"drawer",hR:"highlight",GR:"marker",qS:"promotion",TEXT:"text",hT:"widget"};b3.prototype.u=function(a,b){var c=g.Ee(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
b3.prototype.A=function(a,b){var c=g.Ee(b.target,null,"iv-card-poll",void 0);if(c)if(a.bj)g.de("iv-card-sign-in-button",c).click();else{var d=parseInt(nsa(b.target),10);if(null==a.Ce)a.choices[d].count++,a.Ce=d;else if(a.Ce!=d){var e=a.choices[a.Ce];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Ce=d}else e=a.choices[a.Ce],e.count=Math.max(e.count-1,0),a.Ce=null;Usa(a,c);g.Iq(this.o.videoData.be,{Zd:{action_poll_vote:1},sb:{poll_id:a.id,index:d,session_token:a.nP}});a3(this.o.logger,a.Hc.click,
void 0,5);(c=g.ds())&&a.de&&g.zs(c,a.de)}};g.r(h3,g.A);g.h=h3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.kC(a,b,{id:c});a.namespace="annotations_module";d&&this.ga.set(a,d);e&&this.ma.set(a,e);g.eL(this.context.N,[a])};
g.h.Am=function(){this.context.u.subscribe("resize",this.pn,this)};
g.h.sa=function(){return this.Ka};
g.h.vk=function(a,b,c,d,e,f){this.context.o.ka(a,"click",g.Ra(this.Ao,b,c,d,e||[],f||0),this);this.context.o.ka(a,"touchstart",g.Ra(function(){this.Ou=!1}),this);
this.context.o.ka(a,"touchmove",g.Ra(function(){this.Ou=!0}),this)};
g.h.Ao=function(a,b,c,d,e,f){if(this.Ou)return!1;f&&(f.stopPropagation(),f.preventDefault());$sa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.ue(this.sa())};
g.h.pn=function(){};
g.h.X=function(){this.ga.clear();this.ma.clear();g.A.prototype.X.call(this)};g.r(l3,h3);g.h=l3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.w.length)(a=this.u.getRootNode())?(a=g.Oh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.pn=function(){var a=this.isAvailable();g.Ph(this.sa(),a);g.K(this.context.N.getRootNode(),g.lM.IV_DRAWER_ENABLED,a);B2(this.u)};
g.h.destroy=function(){var a=g.XK(g.KK(this.u));a&&a.Js(!1,void 0);try{this.u.getRootNode().removeChild(this.C)}catch(b){}g.Po(this.V);g.Fp(this.ha);this.da&&this.da.dispose();this.F&&this.F.dispose();h3.prototype.destroy.call(this)};
g.h.KL=function(a){this.ca.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.A.scrollTop+=a};
g.h.SB=function(a){if(!g.Cn(this.u.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.ds(),c=this.o?this.o.card.yd:this.I;b&&c&&D2(b,[c]);this.o=a;p3(this)}if(b="none"!=this.sa().style.display)2==this.context.N.getPresentingPlayerType()?b=1==this.context.N.getAdState():(b=this.context.N.getPlayerState(),c=0==b&&0===this.context.N.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.XK(g.KK(this.u)))&&c.Js(!0,
b));this.za.isActive()||((!this.B||!this.ca.isActive()&&this.aa)&&jta(this,a),this.za.start(910+a.card.teaserDurationMs))}};
g.h.tO=function(a){this.B||(this.o=a,p3(this),jta(this,a),j3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.gE=function(){if(this.B){a3(this.context.logger,q3(this).Hc.close);var a=g.ds();a&&this.L&&g.zs(a,this.L);k3(this)}};
g.h.wE=function(){g.K(this.C,"iv-drawer-scrolled",0<this.A.scrollTop)};
g.h.mG=function(){var a=g.ds(),b=q3(this);b=b?b.yd:this.I;a&&b&&C2(a,[b])};
g.h.lG=function(){var a=g.ds(),b=q3(this);b=b?b.yd:this.I;a&&b&&D2(a,[b])};
g.h.pG=function(){var a=q3(this);a3(this.context.logger,a.Hc.gC);var b=g.ds();b&&a&&C2(b,[a.Yd,a.yd])};
g.h.oG=function(){var a=g.ds(),b=q3(this);a&&b&&D2(a,[b.Yd])};
g.h.nG=function(a){var b=q3(this),c=g.ds();this.o?a?(a=this.context.logger,a3(a,b.Hc.Up),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Yd&&g.zs(c,b.Yd)):(a=this.context.logger,a3(a,b.Hc.Up),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.yd&&g.zs(c,b.yd)):(a=this.context.logger,a3(a,b.Hc.Up),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.I&&g.zs(c,this.I))};g.r(r3,h3);r3.prototype.Am=function(){h3.prototype.Am.call(this);kta(this)};
r3.prototype.show=function(){h3.prototype.show.call(this);var a=g.ds(),b=this.annotation.data;a&&b&&(b=b.session_data)&&C2(a,[g.Wr(b.itct)])};
r3.prototype.hide=function(){h3.prototype.hide.call(this);var a=g.ds(),b=this.annotation.data;a&&b&&(b=b.session_data)&&D2(a,[g.Wr(b.itct)])};g.r(s3,r3);g.h=s3.prototype;g.h.CO=function(a,b,c,d){this.w.stop();if(!this.A){var e=g.Oh(a);this.o||(g.Kh(a,e.width),g.Kh(b,e.width));g.th(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.th(c,"right","1px");this.A=!0;g.Ph(a,!0);this.B=new g.H(function(){g.J(this.sa(),"iv-branding-active")},0,this);
this.B.start()}};
g.h.RF=function(a,b){g.En(this.sa(),"iv-branding-active");this.C=new g.H((0,g.x)(function(){g.Ph(a,!1);this.o||g.Kh(b,0)},this),250);
this.C.start();this.A=!1};
g.h.show=function(){if(!this.isActive){r3.prototype.show.call(this);if(!this.F){g.J(this.sa(),"iv-branding");var a=this.annotation.data;this.u=g.oe("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Ph(this.u,!1);var b=g.oe("DIV","branding-img-container",this.u);this.sa().appendChild(b);(b=this.annotation.kc())&&this.vk(this.u,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.oe("DIV","iv-branding-context-name");
g.ze(c,a.channel_name);var d=g.oe("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=new g.AQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.N),this.o.ba(d);b=g.oe("DIV","iv-branding-context-subscribe-caret");c=g.oe("DIV","branding-context-container-inner",b,c,d);g.Ph(c,!1);d=g.oe("DIV","branding-context-container-outer",c);g.th(d,"right",
a.image_width+"px");this.sa().appendChild(d);this.w=new g.H(g.Ra(this.RF,c,d),500,this);g.B(this,this.w);this.context.o.ka(this.sa(),"mouseover",(0,g.x)(this.CO,this,c,d,b,a.image_height));this.context.o.ka(this.sa(),"mouseout",(0,g.x)(this.w.start,this.w,void 0))}this.F=!0}g.Ph(this.sa(),!0);this.isActive=!0;if(this.u){a=this.u;var e=void 0===e?0:e;b=g.Fh(a);c=g.Oh(a);b=(new g.qh(b.x,b.y,c.width,c.height)).width;g.Bh(a,b);e=new J2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,osa);g.B(this,e);this.context.w.ka(e,
"begin",g.Ra(g.Ph,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(r3.prototype.hide.call(this),g.Ph(this.sa(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);r3.prototype.destroy.call(this)};g.r(t3,r3);g.h=t3.prototype;g.h.show=function(){this.isActive||(r3.prototype.show.call(this),this.P||(lta(this),this.P=!0),g.Ph(this.sa(),!0),g.Vf(function(){g.En(this.sa(),"iv-promo-inactive")},100,this),this.sa().removeAttribute("aria-hidden"),this.isActive=!0,u3(this),nta(this),ota(this,this.F))};
g.h.hide=function(){this.isActive&&(g.J(this.sa(),"iv-promo-inactive"),this.isActive=!1,this.sa().setAttribute("aria-hidden",!0))};
g.h.Ao=function(a,b,c,d,e,f){return this.B?!1:r3.prototype.Ao.call(this,a,b,c,d,e,f)};
g.h.Sr=function(a,b){b.stopPropagation();nta(this);ota(this,a);this.o.focus()};
g.h.vF=function(a){this.I=!0;this.Sr(500,a)};
g.h.uF=function(){this.I=!1;mta(this)};
g.h.mF=function(a){a.stopPropagation();this.hide()};
g.h.nF=function(a){a.stopPropagation();u3(this);this.B=!0;g.J(this.sa(),"iv-promo-collapsed-no-delay");this.C.start()};
g.h.destroy=function(){this.C.dispose();r3.prototype.destroy.call(this)};g.r(v3,g.vL);g.h=v3.prototype;g.h.Pc=function(a,b){if(!rta(this.player.M().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.C1(b);c&&w3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(eta(this.o,b),B2(this.player)),!0}return null};
g.h.getOptions=function(){return rta(this.player.M().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.np=function(){if(this.A){var a=g.QK(this.player).getVideoContentRect(!0);g.Lh(this.A.element,a.width,a.height);g.Bh(this.A.element,a.left,a.top)}if(this.o){var b=g.$K(this.player);a=this.o;b=b.width;g.K(a.C,"iv-drawer-small",426>=b);g.K(a.C,"iv-drawer-big",1280<=b)}};
g.h.iM=function(a){this.Sf(a.state);g.V(a.state,2)&&(this.Ql()&&this.yy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Js(!1))};
g.h.load=function(){g.vL.prototype.load.call(this);this.Sf(g.PK(this.player));this.I++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.WK,this,b,this.I),d=(0,g.x)(function(){this.C=null},this);
g.Vp()&&(c=vta(this,c));c={format:"XML",Gc:c,onError:d,Zd:{}};a.isPharma&&(c.Zd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.M().I.get(b))&&wta(c,b);b=b&&(b.vn||b.un);if(!a.gn||b)a.be?sta(this,a.be,c):(this.w=(0,g.x)(this.PG,this,c),this.player.addEventListener("videodatachange",this.w));g.iL(this.player,this.A.element,4);this.np();(b=g.KB(a))&&Bta(this,b);(b=g.LB(a))&&b.featuredChannel&&Cta(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.Sf=function(a){a=!a.isCued()&&!g.V(a,1024);g.Qu(this.u,a);g.Qu(this.A,a)};
g.h.PG=function(a){var b=this.player.getVideoData();b.be&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),sta(this,b.be,a))};
g.h.unload=function(){g.hR(this.player.app,"annotations_module",void 0);g.zb(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,B2(this.player));this.P=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.vL.prototype.unload.call(this);g.Nu(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.WK=function(a,b,c){this.C=null;!uta(this,b,a)&&(a=g.yq(c)&&c.responseXML?c.responseXML:null)&&(w3(this,a),g.J(this.player.getRootNode(),"iv-module-loaded"))};
g.h.ZA=function(a){a==this.player.getVideoData().videoId&&(this.loaded?xta(this):this.load())};
g.h.Ql=function(){return!!this.o&&this.o.isAvailable()};
g.h.yy=function(){this.Ql();return!!this.o&&this.o.B};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ql();this.o&&(a?c?j3(this.o,c,b):j3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):k3(this.o))};
g.h.Js=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){this.player.M().I.unsubscribe("vast_info_card_add",this.ZA,this);g.En(this.player.getRootNode(),g.lM.IV_DRAWER_OPEN);for(var a=this.L,b=0,c=a.length;b<c;b++)g.Wp(a[b]);this.L.length=0;g.vL.prototype.X.call(this)};g.KL.annotations_module=v3;g.KL.creatorendscreen=O2;})(_yt_player);
