(function(g){var window=this;var T4=function(a,b,c){var d=b.wa();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.wc(c?c:"mqdefault.jpg");var f=b instanceof g.aB&&b.lengthSeconds?g.hM(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.oC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.aB?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Pk||g.gM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.lh(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.pC&&(d.playlist_length=b.getLength());a.update(d)},U4=function(a){g.R.call(this,{D:"div",
Y:["ytp-upnext","ytp-player-content"],O:{"aria-label":"{{aria_label}}"},J:[{D:"div",H:"ytp-cued-thumbnail-overlay-image",O:{style:"{{background}}"}},{D:"span",H:"ytp-upnext-top",J:[{D:"span",H:"ytp-upnext-header",W:"Up Next"},{D:"span",H:"ytp-upnext-title",W:"{{title}}"},{D:"span",H:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",H:"ytp-upnext-autoplay-icon",O:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{D:"svg",O:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{D:"circle",
H:"ytp-svg-autoplay-circle",O:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",H:"ytp-svg-autoplay-ring",O:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",H:"ytp-svg-fill",O:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",H:"ytp-upnext-bottom",J:[{D:"span",H:"ytp-upnext-cancel"},{D:"span",H:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.R({D:"button",Y:["ytp-upnext-cancel-button","ytp-button"],O:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.B(this,this.B);this.B.ka("click",this.pK,this);this.B.ba(b);this.u=a;this.L=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.H(this.An,5E3,this);g.B(this,this.G);this.I=0;g.kL(this.u,this.element,this,18788);this.K(this.o["ytp-upnext-autoplay-icon"],"click",this.cM);this.bA();this.K(a,"autonavvisibility",
this.bA);this.K(a,"mdxnowautoplaying",this.sL);this.K(a,"mdxautoplaycanceled",this.tL);this.K(a,"mdxautoplayupnext",this.BC);3==this.u.getPresentingPlayerType()&&(a=(a=g.RK(g.KK(this.u)))?a.dF():null)&&this.BC(a);g.K(this.element,"ytp-upnext-mobile",this.u.M().o)},V4=function(a,b){if(!a.w){g.Qo("a11y-announce","Up Next "+a.A.title);
a.I=(0,g.N)();a.w=new g.H((0,g.x)(a.Hq,a,b),25);a.Hq(b);var c=b||g.Q(a.u.M().experiments,"autoplay_time")||1E4;a.u.na("onAutonavCoundownStarted",c)}g.En(a.element,"ytp-upnext-autoplay-paused")},X4=function(a){W4(a);
a.I=(0,g.N)();a.Hq();g.J(a.element,"ytp-upnext-autoplay-paused")},W4=function(a){a.w&&(a.w.dispose(),a.w=null)},Y4=function(a,b){g.R.call(this,{D:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},Zua=function(a){Y4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.R({D:"div",H:"ytp-subscribe-card",J:[{D:"img",H:"ytp-author-image",O:{src:b.Jd}},{D:"div",H:"ytp-subscribe-card-right",J:[{D:"div",H:"ytp-author-name",W:b.author},{D:"div",H:"html5-subscribe-button-container"}]}]});g.B(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.AQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.Og,b.subscribed,"trailer-endscreen",null,null,a);g.B(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},Z4=function(a){var b=a.M(),c=g.Dt||g.wh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.R.call(this,{D:"a",Y:e,O:{href:"{{url}}",target:d?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{D:"div",H:"ytp-videowall-still-image",O:{style:"{{background}}"}},{D:"span",H:"ytp-videowall-still-info",J:[{D:"span",H:"ytp-videowall-still-info-bg",J:[{D:"span",H:"ytp-videowall-still-info-content",O:c,J:[{D:"span",H:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",H:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",H:"ytp-videowall-still-info-live",W:"Live"},{D:"span",H:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{D:"span",H:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",H:"ytp-videowall-still-listlabel-length",J:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{D:"span",H:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",H:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.w=new g.Gr(this);g.B(this,this.w);this.ka("click",this.onClick);this.ka("keypress",this.B);this.w.K(a,"videodatachange",this.A);g.lL(a,this.element,this);this.A()},$4=function(a){Y4.call(this,a,"videowall-endscreen");
var b=this;this.N=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.I=!1;this.G=null;this.w=new g.TQ(this);g.B(this,this.w);this.F=new g.H(function(){g.J(b.element,"ytp-show-tiles")},0);
g.B(this,this.F);var c=new g.R({D:"button",Y:["ytp-button","ytp-endscreen-previous"],O:{"aria-label":"Previous"},J:[g.BM()]});g.B(this,c);c.ba(this.element);c.ka("click",this.rH,this);this.table=new g.Mu({D:"div",H:"ytp-endscreen-content"});g.B(this,this.table);this.table.ba(this.element);c=new g.R({D:"button",Y:["ytp-button","ytp-endscreen-next"],O:{"aria-label":"Next"},J:[g.CM()]});g.B(this,c);c.ba(this.element);c.ka("click",this.qH,this);this.u=new U4(a);g.B(this,this.u);g.iL(this.player,this.u.element,
4);this.hide()},a5=function(a){return g.jL(a.player)&&a.Tv()&&!a.B},$ua=function(a,b){return(0,g.Dc)(b.suggestions,function(c){c=g.jM(a.N.M(),c);
g.B(a,c);return c})},b5=function(a){var b=a.Rs();
b!==a.I&&(a.I=b,a.player.S("autonavvisibility"))},c5=function(a){g.vL.call(this,a);
this.endScreen=null;this.listeners=new g.Gr(this);g.B(this,this.listeners);this.o=a.M();ava(a)?this.endScreen=new $4(this.player):this.o.Ta?this.endScreen=new Zua(this.player):this.endScreen=new Y4(this.player);g.B(this,this.endScreen);g.iL(this.player,this.endScreen.element,4);this.LB();this.listeners.K(a,"videodatachange",this.LB,this);this.listeners.K(a,g.nC("endscreen"),this.nH,this);this.listeners.K(a,"crx_endscreen",this.oH,this)},ava=function(a){a=a.M();
return a.Aa&&!a.Ta};
g.r(U4,g.R);g.h=U4.prototype;g.h.An=function(){this.C&&(this.G.stop(),this.bb(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.bA=function(){g.Qu(this,g.LK(this.u));g.oL(this.u,this.element,g.LK(this.u))};
g.h.RL=function(){window.focus();this.An()};
g.h.hide=function(){g.R.prototype.hide.call(this)};
g.h.Hq=function(a){a=a||g.Q(this.u.M().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.N)()-this.I,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?this.select(!0):this.w&&this.w.start()};
g.h.select=function(a){a=void 0===a?!1:a;if(g.P(this.u.M().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"==b?Notification.requestPermission():"granted"!=b||document.hasFocus()||(b=this.A.wa(),this.An(),this.C=new Notification("Up Next",{body:b.title,icon:b.wc()}),this.F=this.K(this.C,"click",this.RL),this.G.start())}W4(this);this.u.nextVideo(!1,a)};
g.h.cM=function(a){!g.ye(this.B.element,g.Gp(a))&&g.IN(a,this.u)&&this.select()};
g.h.pK=function(){g.NK(this.u,!0)};
g.h.sL=function(a){this.u.getPresentingPlayerType();this.show();V4(this,a)};
g.h.BC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.wa().videoId==a.wa().videoId||(this.A=a,T4(this,a,"hqdefault.jpg"))};
g.h.tL=function(){this.u.getPresentingPlayerType();W4(this);this.hide()};
g.h.X=function(){W4(this);this.An();g.R.prototype.X.call(this)};g.r(Y4,g.R);g.h=Y4.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Tv=function(){return!1};
g.h.Rs=function(){return!1};
g.h.ay=function(){return!1};g.r(Zua,Y4);g.r(Z4,g.R);Z4.prototype.select=function(){var a=this.suggestion.wa().videoId,b=this.suggestion.getPlaylistId();(g.tT(this.api.app,a,this.suggestion.Pb,b,void 0,void 0)||this.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.nL(this.api,this.element)};
Z4.prototype.onClick=function(a){g.IN(a,this.api,this.u,this.suggestion.Pb||void 0)&&this.select()};
Z4.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.Lp(a)||(this.select(),g.Kp(a))}};
Z4.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.M();this.u=a.oc?!1:b.u};g.r($4,Y4);g.h=$4.prototype;g.h.create=function(){Y4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=$ua(this,a),this.videoData=a);this.Ig();this.w.K(this.player,"appresize",this.Ig);this.w.K(this.player,"onVideoAreaChange",this.Ig);this.w.K(this.player,"videodatachange",this.sH);this.w.K(this.player,"autonavchange",this.Ss);this.w.K(this.player,"autonavcancel",this.pH);a=this.videoData.autonavState;a!==this.G&&this.Ss(a);this.w.K(this.element,"transitionend",this.pN)};
g.h.destroy=function(){g.Ir(this.w);g.Je(this.stills);this.stills=[];this.suggestions=null;Y4.prototype.destroy.call(this);g.En(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.Tv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){Y4.prototype.show.call(this);g.En(this.element,"ytp-show-tiles");this.player.M().o?g.vn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.NK(this.player,!1);a5(this)?(b5(this),2===this.videoData.autonavState?this.player.M().fa("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):V4(this.u):3===this.videoData.autonavState&&X4(this.u)):(g.NK(this.player,!0),b5(this))};
g.h.hide=function(){Y4.prototype.hide.call(this);X4(this.u);b5(this)};
g.h.pN=function(a){g.Gp(a)===this.element&&this.Ig()};
g.h.Ig=function(){if(this.suggestions&&this.suggestions.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.$K(this.N,!0,this.N.isFullscreen()),b=g.dC(this.N);b&&(b=b.lc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;c=this.player.M().fa("web_player_no_endscreen_crop")?1:1.21;m*=g.Nd(a.width/m||1,1,c);n*=g.Nd(a.height/n||1,1,c);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Lh(a,m,n);g.th(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;T4(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",
a5(this));b5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),p=g.Od(p+this.A,l),0!==t){u=this.stills[c];u||(u=new Z4(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-z-4,E=Math.floor(m*(f+t)/b)-C-4;g.Bh(u.element,C,z);g.Lh(u.element,E,D);g.th(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1===t);g.K(u.element,
"ytp-videowall-still-large",2<t);t=u;p=this.suggestions[p];t.suggestion!==p&&(t.suggestion=p,u=t.api.M(),z=g.Cn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",T4(t,p,z),g.Ly(u)&&(u=p.lh(),u=g.zd(u,g.FH({},"emb_rel_end")),t.la("url",u)),(p=(p=p.Pb)&&p.itct)&&g.mL(t.api,t.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ue(e.element),g.Ie(e);this.stills.length=c}};
g.h.sH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=$ua(this,a),this.videoData=a,this.Ig())};
g.h.qH=function(){this.A+=this.stills.length;this.Ig()};
g.h.rH=function(){this.A-=this.stills.length;this.Ig()};
g.h.ay=function(){return!!this.u.w};
g.h.Ss=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,W4(this.u),this.Ha()&&this.Ig()):(this.C=!0,this.Ha()&&a5(this)&&(2===a?V4(this.u):3===a&&X4(this.u)))};
g.h.pH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.oL(this.N,this.stills[a].element,!0);this.Ss(1)}else this.B=null,this.C=!1;this.Ig()};
g.h.Rs=function(){return this.Ha()&&a5(this)};g.r(c5,g.vL);g.h=c5.prototype;g.h.Ay=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!ava(this.player)||b;var c=a.lj||g.Uy(a.Pa),d=g.NS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.zy=function(){return this.endScreen.Rs()};
g.h.YF=function(){return this.zy()?this.endScreen.ay():!1};
g.h.X=function(){g.hR(this.player.app,"endscreen",void 0);g.vL.prototype.X.call(this)};
g.h.load=function(){g.vL.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.vL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.nH=function(a){this.Ay()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.oH=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.LB=function(){g.hR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.kC(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.kC(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.eL(this.player,[a,b])};g.KL.endscreen=c5;})(_yt_player);
