(function(g){var window=this;var Tva=function(a,b){return g.Kb(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.G)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.w,b,c)},Uva=function(a,b){var c=[];
g.ik(b,function(d){try{var e=g.ao.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.$n(e)&&c.push(d)},a);
return c},Vva=function(a,b){var c=Uva(a,b);
(0,g.y)(c,function(d){g.ao.prototype.remove.call(this,d)},a)},Wva=function(a){if(a.Tc){if(a.Tc.locationOverrideToken)return{locationOverrideToken:a.Tc.locationOverrideToken};
if(null!=a.Tc.latitudeE7&&null!=a.Tc.longitudeE7)return{latitudeE7:a.Tc.latitudeE7,longitudeE7:a.Tc.longitudeE7}}return null},Xva=function(a,b){g.ab(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},Yva=function(a,b){var c=b instanceof g.uc?b:g.yc(b,/^data:image\//i.test(b));
a.src=g.vc(c)},b6=function(){},Zva=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},$va=function(a){if(a.Fd&&"function"==typeof a.Fd)return a.Fd();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Gb(a)},awa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.te&&"function"==typeof a.te)var c=a.te();else if(a.Fd&&"function"==typeof a.Fd)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Hb(a);d=$va(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},bwa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Mo[a]=!0;
var c=g.Ko();c&&c.publish.apply(c,arguments);g.Mo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",cwa(this,a.capabilities||""),dwa(this,a.experiments||""))},cwa=function(a,b){a.capabilities.clear();
(0,g.ve)(b.split(","),g.Ra(Tva,ewa)).forEach(function(c){a.capabilities.add(c)})},dwa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},fwa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},gwa=function(a){return new e6(a)},hwa=function(a){return g.La(a)?(0,g.Dc)(a,gwa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.La(a)?"["+(0,g.Dc)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},iwa=function(a){return(0,g.Dc)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Ya(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Cs)(),c=(0,g.Bs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},jwa=function(){var a=(0,g.Bs)();
a&&Vva(a,a.o.Zf(!0))},m6=function(){var a=g.Es("yt-remote-connected-devices")||[];
g.sb(a);return a},kwa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Dc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},lwa=function(a){g.Ds("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Es("yt-remote-device-id");a||(a=i6(),g.Ds("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.ab(a,b);g.Fs()&&g.ub(a,b);a=kwa(a);if(g.bb(a))try{g.Oq("remote_sid")}catch(c){}else try{g.Mq("remote_sid",a.join(","),-1)}catch(c){}},mwa=function(){return g.Es("yt-remote-session-browser-channel")},nwa=function(){return g.Es("yt-remote-local-screens")||[]},owa=function(){g.Ds("yt-remote-lounge-token-expiration",!0,86400)},pwa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Dc)(nwa(),function(d){return d.loungeToken}),c=(0,g.Dc)(a,function(d){return d.loungeToken});
(0,g.ui)(c,function(d){return!g.ab(b,d)})&&owa();
g.Ds("yt-remote-local-screens",a,31536E3)},qwa=function(a,b){g.Ds("yt-remote-session-browser-channel",a);
g.Ds("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.ab(c,d)||c.push(d);lwa(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.eb(a,o6());lwa(a)},rwa=function(){if(!r6){var a=g.lo();
a&&(r6=new g.Vn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},swa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},twa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?uwa(a.shift(),function(){s6(a)}):t6()},vwa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},uwa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=twa();
a&&a(!1,"No cast extension found")},xwa=function(){if(wwa){var a=2,b=twa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;uwa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},ywa=function(){xwa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Ad=b;this.B=(0,g.x)(this.iF,this);this.o=!1;this.u=0;this.w=this.Ga=null;this.A=[]},v6=function(a,b,c){g.A.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Ad=b;this.u=(0,g.x)(this.jF,this);this.o=[]},w6=function(a){a.Ga=g.Vf(a.u,a.Ad);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Zva(a)},y6=function(){},z6=function(){},zwa=function(){},Bwa=function(a){return(a=Awa(a))?new ActiveXObject(a):new XMLHttpRequest},Awa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.D1(this);this.u=new g.Uf;this.u.setInterval(250)},Dwa=function(a,b,c){a.Dj=1;
a.Wg=Z5(b.clone());a.Vi=c;a.C=!0;Cwa(a,null)},B6=function(a,b,c,d,e){a.Dj=1;
a.Wg=Z5(b.clone());a.Vi=null;a.C=c;e&&(a.QB=!1);Cwa(a,d)},Cwa=function(a,b){a.tk=(0,g.G)();
C6(a);a.Lh=a.Wg.clone();$5(a.Lh,"t",a.F);a.Om=0;a.Mc=a.o.dr(a.o.Em()?b:null);0<a.Qr&&(a.zp=new v6((0,g.x)(a.LC,a,a.Mc),a.Qr));a.A.ka(a.Mc,"readystatechange",a.aO);var c=a.vi?g.Qb(a.vi):{};a.Vi?(a.gq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Mc.send(a.Lh,a.gq,a.Vi,c)):(a.gq="GET",a.QB&&!g.ke&&(c.Connection="close"),a.Mc.send(a.Lh,a.gq,null,c));a.o.bf(1)},Gwa=function(a,b,c){for(var d=!0;!a.ci&&a.Om<c.length;){var e=Ewa(a,c);
if(e==D6){4==b&&(a.mh=4,E6(15),d=!1);break}else if(e==Fwa){a.mh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.mh=1,E6(17),d=!1);a.df=a.df&&d;d||(G6(a),H6(a))},Ewa=function(a,b){var c=a.Om,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return Fwa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Om=d+c;return e},Iwa=function(a,b){a.tk=(0,g.G)();
C6(a);var c=b?window.location.hostname:"";a.Lh=a.Wg.clone();Y5(a.Lh,"DOMAIN",c);Y5(a.Lh,"t",a.F);try{a.kf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.mh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in Hwa)k=I6[l]=Hwa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Wc(g.Zb("b/12014412"),d+"</body></html>");a.kf.open();a.kf.write(g.Rc(c));a.kf.close();a.kf.parentWindow.m=(0,g.x)(a.tN,a);a.kf.parentWindow.d=(0,g.x)(a.YA,a,!0);a.kf.parentWindow.rpcClose=(0,g.x)(a.YA,a,!1);c=a.kf.createElement("DIV");a.kf.parentWindow.document.body.appendChild(c);d=g.xc(a.Lh.toString());d=g.dd(g.vc(d));d=g.Wc(g.Zb("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Xc(c,d);a.o.bf(1)},C6=function(a){a.Pu=(0,g.G)()+a.B;
Jwa(a,a.B)},Jwa=function(a,b){if(null!=a.Gk)throw Error("WatchDog timer not null");
a.Gk=J6((0,g.x)(a.BN,a),b)},K6=function(a){a.Gk&&(g.v.clearTimeout(a.Gk),a.Gk=null)},H6=function(a){a.o.wx()||a.ci||a.o.bo(a)},G6=function(a){K6(a);
g.Ie(a.zp);a.zp=null;a.u.stop();g.Qqa(a.A);if(a.Mc){var b=a.Mc;a.Mc=null;b.abort();b.dispose()}a.kf&&(a.kf=null)},F6=function(a,b){try{a.o.QA(a,b),a.o.bf(4)}catch(c){}},Lwa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Kwa(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Lwa(a,b,c,d,f)},f)})}},Kwa=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Yva(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Mwa=function(a){this.o=a;
this.u=new y6},Nwa=function(a){var b=M6(a.o,a.Rk,"/mail/images/cleardot.gif");
Z5(b);Lwa(b.toString(),5E3,(0,g.x)(a.cE,a),3,2E3);a.bf(1)},O6=function(a){var b=a.o.I;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Vd=new A6(a,void 0,void 0,void 0),a.Vd.vi=a.Or,b=a.o,b=M6(b,b.Em()?a.xl:null,a.Pr),E6(5),!g.ie||g.Md(10))$5(b,"TYPE","xmlhttp"),B6(a.Vd,b,!1,a.xl,!1);else{$5(b,"TYPE","html");var c=a.Vd;a=!!a.xl;c.Dj=3;c.Wg=Z5(b.clone());Iwa(c,a)}},P6=function(a){g.hf.call(this);
this.headers=new g.Nm;this.T=a||null;this.w=!1;this.R=this.o=null;this.ha=this.I="";this.C=0;this.A="";this.B=this.Z=this.G=this.V=!1;this.F=0;this.P=null;this.da="";this.L=this.ca=!1},Owa=function(a){return g.ie&&g.Ld(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Pwa=function(a){return"content-type"==a.toLowerCase()},Rwa=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;Qwa(a);Q6(a)},Qwa=function(a){a.V||(a.V=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Twa=function(a){if(a.w&&"undefined"!=typeof g.I1)if(a.R[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.Vf(a.MA,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.od(1,String(a.I));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Swa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";Qwa(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){Uwa(a);
var c=a.o,d=a.R[0]?g.Ia:null;a.o=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Uwa=function(a){a.o&&a.L&&(a.o.ontimeout=null);
a.P&&(g.v.clearTimeout(a.P),a.P=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.ha+" "+a.I+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.I=null!=b?b:null;this.C=c||!1},Vwa=function(a,b){this.o=a;
this.map=b;this.context=null},Wwa=function(a){g.Ke.call(this,"statevent",a)},Xwa=function(a,b){g.Ke.call(this,"timingevent",a);
this.size=b},Ywa=function(a){g.Ke.call(this,"serverreachability",a)},axa=function(a){Zwa(a);
if(3==a.o){var b=a.hm++,c=a.On.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.Dj=2;b.Wg=Z5(c.clone());Yva(new Image,b.Wg.toString());b.tk=(0,g.G)();C6(b)}$wa(a)},bxa=function(a){a.BE(1,0);
a.On=M6(a,null,a.Nr);W6(a)},Zwa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.jc&&(a.jc.cancel(),a.jc=null);a.cg&&(g.v.clearTimeout(a.cg),a.cg=null);X6(a);a.Pd&&(a.Pd.cancel(),a.Pd=null);a.fh&&(g.v.clearTimeout(a.fh),a.fh=null)},cxa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Vwa(a.KJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Pd||a.fh||(a.fh=J6((0,g.x)(a.XA,a),0),a.vj=0)},exa=function(a,b){if(1==a.o){if(!b){a.hm=Math.floor(1E5*Math.random());
var c=a.hm++,d=new A6(a,"",c,void 0);d.vi=null;var e=Y6(a),f=a.On.clone();Y5(f,"RID",c);Y5(f,"CVER","1");V6(a,f);Dwa(d,f,e);a.Pd=d;a.o=2}}else 3==a.o&&(b?dxa(a,b):0==a.u.length||a.Pd||dxa(a))},dxa=function(a,b){if(b)if(6<a.di){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.hm-1;var d=Y6(a)}else c=b.G,d=b.Vi;else c=a.hm++,d=Y6(a);var e=a.On.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.Qj);V6(a,e);c=new A6(a,a.w,c,a.vj+1);c.vi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Pd=c;Dwa(c,e,d)},V6=function(a,b){if(a.wd){var c=a.wd.Sw();
c&&g.zb(c,function(d,e){Y5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.di&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.di?e:f-d;try{g.zb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},fxa=function(a){a.jc||a.cg||(a.F=1,a.cg=J6((0,g.x)(a.WA,a),0),a.nj=0)},Z6=function(a){if(a.jc||a.cg||3<=a.nj)return!1;
a.F++;a.cg=J6((0,g.x)(a.WA,a),gxa(a,a.nj));a.nj++;return!0},N6=function(a,b,c){a.eq=c;
a.yf=b.rg;a.C||bxa(a)},X6=function(a){null!=a.ji&&(g.v.clearTimeout(a.ji),a.ji=null)},gxa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.wd&&(c=null);var d=(0,g.x)(a.LO,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),Z5(c));Kwa(c.toString(),1E4,d)}else E6(2);hxa(a,b)},hxa=function(a,b){a.o=0;
a.wd&&a.wd.iw(b);$wa(a);Zwa(a)},$wa=function(a){a.o=0;
a.yf=-1;if(a.wd)if(0==a.A.length&&0==a.u.length)a.wd.Tq();else{g.ib(a.A);var b=g.ib(a.u);a.A.length=0;a.u.length=0;a.wd.Tq(b)}},M6=function(a,b,c){var d=g.Ym(c);
if(""!=d.o)b&&g.Sm(d,b+"."+d.o),g.Tm(d,d.A);else{var e=window.location;d=bwa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.kl&&g.zb(a.kl,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.di);V6(a,d);return d},J6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Wwa(a7,a))},ixa=function(){},jxa=function(){this.o=[];
this.u=[]},kxa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.H(this.lN,0,this);g.B(this,this.o);this.Ad=5E3;this.u=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.P=a;
this.C=b;this.w=new g.Un;this.u=new b7(this.oO,this);this.o=null;this.ub=!1;this.B=null;this.I="";this.G=this.A=0;this.F=[];this.L=c||!1},lxa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.eq,sessionId:a.o.w,arrayId:a.o.Qj}},mxa=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&exa(a.o),axa(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},nxa=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.od(4,a))||"";b&&(this.port=":"+b);this.domain=g.pd(a)||"";a=g.Jc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.qc(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.zd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.A,d,!0),onError:g.Ra(a.w,e),Ud:g.Ra(a.B,e)};c&&(a.sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Eq(b,a)},rxa=function(){var a=oxa;
pxa();h7.push(a);qxa(h7)},i7=function(a,b){pxa();
var c=h7,d=sxa(a,String(b));g.bb(c)?txa(d):(qxa(c),(0,g.y)(c,function(e){e(d)}))},pxa=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",h7,void 0))},txa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},qxa=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},sxa=function(a,b){var c=((0,g.G)()-uxa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.O.call(this);
this.F=a;this.o=[]},vxa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},wxa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.ve)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=vxa(a,b[d])||c;return c},xxa=function(a,b){var c=a.o.length;
a.o=(0,g.ve)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.O.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Ga=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},yxa=function(a){if(a.o.length){var b=(0,g.Dc)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.tF,a),(0,g.x)(a.sF,a))}},o7=function(a){var b=hwa(nwa());
b=(0,g.ve)(b,function(c){return!c.uuid});
return wxa(a,b)},q7=function(a,b){pwa((0,g.Dc)(a.o,fwa));
b&&owa()},s7=function(a,b){g.O.call(this);
this.C=b;var c=g.Es("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Kk(this.o))},zxa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Hb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Kk(a.o)),a.o=b,a.S("screenChange"));Axa(a)},u7=function(a){isNaN(a.w)||g.Jo(a.w);
a.w=g.Ho((0,g.x)(a.gu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Bxa=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Ub("Requesting availability of screen w/o lounge token.")});
return b},Axa=function(a){a=g.Hb(g.Bb(a.o,function(b){return b}));
g.sb(a);a.length?g.Ds("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Cxa(this)},Exa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.he();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);zxa(a.u,l,function(m){e(m?l:null)})}else c?Dxa(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));zxa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},Fxa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Dxa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Eq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Gxa=function(a){a.o=a.w.he();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},Cxa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.CF,a));Gxa(a);a.A=hwa(g.Es("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.he,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ds("yt-remote-automatic-screen-cache",(0,g.Dc)(a.A,fwa)));x7(a);a.B[b.uuid]=b.id;g.Ds("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Es("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.O.call(this);
this.R=c;this.I=a;this.u=b;this.w=null},z7=function(a,b){i7(a.R,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.vP,this);this.B=(0,g.x)(this.JN,this);this.A=g.Ho((0,g.x)(function(){Hxa(this,null)},this),12E4)},Ixa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Kk(b))},Hxa=function(a,b){g.Jo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.pp,a),d=(0,g.x)(a.le,a);a.mx(b,c,d,5)}}else a.le(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.P="";this.T=c;this.B=null;this.F=g.Ia;this.C=NaN;this.L=(0,g.x)(this.yP,this);this.o=g.Ia},Jxa=function(a){a.o=a.I.RC(a.P,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ia;
this.pp(b)},a),(0,g.x)(function(b){this.o=g.Ia;
this.le(b)},a))},Kxa=function(a){var b={};
b.pairingCode=a.P;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}rwa()&&(b.env_useStageMdx=1);return g.xd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Ho((0,g.x)(this.Rj,this,null),150)},D7=function(a,b,c,d){g.O.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.wM,this)},Lxa=function(a,b){return b?g.Ya(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},oxa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.Ie(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.VA,a,b)),b.w?a.S("yt-remote-cast2-session-change",b.w):c&&a.o.Rj(null)):a.S("yt-remote-cast2-session-change",null))},Mxa=function(a){var b=a.u.QC(),c=a.o&&a.o.u;
a=(0,g.Dc)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Lxa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Sxa=function(a,b,c,d,e,f,k){Nxa()?Oxa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Pxa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Pxa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Qxa(),c(!1))},d?g.To("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?ywa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(xwa(),s6(Rxa.map(vwa))))):H7("Cannot initialize because not running Chrome")},Qxa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Txa(!1);g.Po(M7);M7.length=0},N7=function(){return!!g.Es("yt-remote-cast-installed")},Uxa=function(){var a=g.Es("yt-remote-cast-receiver");
return a?a.friendlyName:null},Vxa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},Wxa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Oo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Nxa=function(){var a=0<=g.Jc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Dt||a},Xxa=function(a,b){L7().init(a,b)},Oxa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ds("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Ds("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Ds("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Pxa=function(a,b){K7(!0);
I7(!1);Xxa(a,function(c){c?(Txa(!0),g.Qo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Qxa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Ds("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Txa=function(a){H7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.P=!1;this.I=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.P=!1;a.hasNext=!1;a.F=0;a.C=(0,g.G)();a.B=0;a.u=0;a.G=0;a.I=0;a.A=NaN;a.w=!1},T7=function(a){return a.eb()?((0,g.G)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.G)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.G)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Rb(a.o);b.hasPrevious=a.P;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.O.call(this);
this.o=0;this.A=a;this.C=[];this.B=new jxa;this.w=this.u=null;this.I=(0,g.x)(this.sK,this);this.F=(0,g.x)(this.jm,this);this.G=(0,g.x)(this.rK,this);this.P=(0,g.x)(this.DK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Su,this),Yxa(this))):c=3;0!=c&&(b?this.Su(c):g.Ho((0,g.x)(function(){this.Su(c)},this),0));
var d=Wxa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.P)},$7=function(a){return new R7(a.A.getPlayerContextData())},Yxa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Ra(this.tM,b),this))},a)},Zxa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){Zxa(a);
a.A.setPlayerContextData(X7(b));Yxa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.I),a.w.removeMediaListener(a.F),a.jm(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.I),a.w.addMediaListener(a.F),a.w.media.length&&a.jm(a.w.media[0]))},$xa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Ub("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ub("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.O.call(this);
this.B=NaN;this.L=!1;this.G=this.F=this.I=this.P=NaN;this.R=[];this.A=this.C=this.w=this.Va=this.o=null;this.V=a;this.R.push(g.Ep(window,"beforeunload",(0,g.x)(this.lF,this)));this.u=[];this.Va=new R7;this.T=b.id;this.o=aya(this,c);this.o.subscribe("handlerOpened",this.wK,this);this.o.subscribe("handlerClosed",this.tK,this);this.o.subscribe("handlerError",this.uK,this);this.o.subscribe("handlerMessage",this.vK,this);nxa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Va.videoId;
g.Fs()&&g.Ds("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},aya=function(a,b){return new c7(f7(a.V,"/bc"),b)},h8=function(a,b){a.S("proxyStateChange",b)},bya=function(a){a.B=g.Ho((0,g.x)(function(){g8("Connecting timeout");
this.tj(1)},a),2E4)},i8=function(a){g.Jo(a.B);
a.B=NaN},j8=function(a){g.Jo(a.P);
a.P=NaN},cya=function(a){k8(a);
a.I=g.Ho((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Jo(a.I);
a.I=NaN},eya=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.kx()&&a.Va.reset(),h8(a,1),l8(a,"getNowPlaying"),dya(a)):a.tj(1)},fya=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Va.videoId&&(g.Nb(b.params)?a.Va.o=null:a.Va.o=b.params,a.S("remotePlayerChange"))},gya=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Va.listId=b.params.listId||a.Va.listId;W7(a.Va,c,d);a.S("remoteQueueChange")},iya=function(a,b){b.params=b.params||{};
gya(a,b);hya(a,b);a.S("autoplayDismissed")},hya=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Va,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Va.playerState&&(c=-1E3);a.Va.playerState=c;c=Number(b.params.loadedTime);a.Va.I=isNaN(c)?0:c;c=Number(b.params.duration);a.Va.G=isNaN(c)?0:c;c=a.Va;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Va;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Va.playerState?cya(a):k8(a);a.S("remotePlayerChange")},jya=function(a,b){if(-1E3!=
a.Va.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Va.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Va,isNaN(c)?0:c);a.S("remotePlayerChange")}},kya=function(a,b){var c="true"==b.params.muted;
a.Va.volume=parseInt(b.params.volume,10);a.Va.muted=c;a.S("remotePlayerChange")},lya=function(a,b){a.C=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},mya=function(a,b){var c="true"==b.params.hasNext;
a.Va.P="true"==b.params.hasPrevious;a.Va.hasNext=c;a.S("previousNextChange")},dya=function(a){g.Jo(a.G);
a.G=g.Ho((0,g.x)(a.tj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Kk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.zd=a;this.u=[];this.u.push(this.zd.$_s("screenChange",(0,g.x)(this.tP,this)));this.u.push(this.zd.$_s("onlineScreenChange",(0,g.x)(this.UL,this)))},rya=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;jwa();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),rwa()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",o8,void 0));nya();var c=p8();if(!c){var d=new v7(n8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Sxa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Kk(b)),s8.push(g.Oo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.Oo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Oo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Oo("yt-remote-cast2-session-change",oya)),s8.push(g.Oo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Vxa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.xo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Kk(a)),pya(a),c.start(),q8()||qya())},tya=function(){var a=sya();
N7()&&g.Es("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},sya=function(){var a=p8().zd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return iwa(a)},y8=function(){var a=uya();
!a&&N7()&&Uxa()&&(a={key:"cast-selector-receiver",name:Uxa()});return a},uya=function(){var a=sya(),b=w8();
b||(b=u8());return g.Ya(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().he();return k6(b,a)},oya=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},vya=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},wya=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||vya("");g.Ga("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.Fs();
if(!a)return null;var b=p8().he();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{vya(a.id);var c=new f8(n8,a,v8());c.connect(b,wya());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},qya=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),Vxa(),r8("Skipping connecting because no session screen found."))},nya=function(){var a=v8();
if(g.Nb(a)){a=o6();var b=g.Es("yt-remote-session-name")||"",c=g.Es("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},pya=function(a){a?(g.Ds("yt-remote-session-app",a.app),g.Ds("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.w=new g.Gr(this);g.B(this,this.w);this.w.K(b,"onCaptionsTrackListChanged",this.qL);this.w.K(b,"captionschanged",this.qK);this.w.K(b,"captionssettingschanged",this.eC);this.w.K(b,"videoplayerreset",this.qp);this.w.K(b,"mdxautoplaycancel",this.bE);this.T=this.w.K(b,"onVolumeChange",this.tA);this.G=!1;this.o=c;c.ea();c.subscribe("proxyStateChange",this.PA,this);c.subscribe("remotePlayerChange",this.om,this);c.subscribe("remoteQueueChange",this.qp,this);c.subscribe("autoplayUpNext",
this.dA,this);c.subscribe("previousNextChange",this.KA,this);c.subscribe("nowAutoplaying",this.FA,this);c.subscribe("autoplayDismissed",this.cA,this);this.suggestion=null;this.I=new g.JC(64);this.A=new g.H(this.cC,500,this);g.B(this,this.A);this.C=new g.H(this.dC,1E3,this);g.B(this,this.C);this.L=new u6(this.UO,0,this);g.B(this,this.L);this.F={};this.R=new g.H(this.DC,1E3,this);g.B(this,this.R);this.P=new v6(this.yI,1E3,this);g.B(this,this.P);this.V=g.Ia;this.eC();this.qp();this.om()},H8=function(a,
b){var c=a.B,d=a.u.getVideoData().lengthSeconds;
c.R=b||0;c.player.S("progresssync",b,d)},xya=function(a){H8(a,0);
a.A.stop();I8(a,new g.JC(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.Tb(c,b));a.o.VB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.Af,Wva(c));I8(a,new g.JC(1))},yya=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{Lx:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.I;if(!g.PC(c,b)){var d=g.V(b,2);d!=g.V(a.I,2)&&g.VS(a.u.app,d);a.I=b;zya(a.B,c,b)}},M8=function(a){g.R.call(this,{D:"div",
H:"ytp-remote",J:[{D:"div",H:"ytp-remote-display-status",J:[{D:"div",H:"ytp-remote-display-status-icon",J:[g.zM()]},{D:"div",H:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.lN(this,250);g.B(this,this.u);this.w=a;this.K(a,"presentingplayerstatechange",this.A);Aya(this,g.PK(a))},Aya=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.gM("Error on $RECEIVER_NAME",c):b.eb()||g.V(b,4)?g.gM("Playing on $RECEIVER_NAME",c):g.gM("Connected to $RECEIVER_NAME",c);a.la("statustext",c);a.u.show()}else a.u.hide()},N8=function(a,b){g.iO.call(this,"Play on",0,a,b);
this.A=a;this.G={};this.K(a,"onMdxReceiversChange",this.L);this.K(a,"presentingplayerstatechange",this.L);this.L()},O8=function(){g.R.call(this,{D:"div",
H:"ytp-mdx-popup-dialog",O:{role:"dialog"},J:[{D:"div",H:"ytp-mdx-popup-dialog-inner-content",J:[{D:"div",H:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",H:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",H:"ytp-mdx-privacy-popup-buttons",J:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.u=new g.lN(this,250);this.cancelButton=this.o["ytp-mdx-privacy-popup-cancel"];this.confirmButton=this.o["ytp-mdx-privacy-popup-confirm"];g.B(this,this.u);this.K(this.cancelButton,"click",this.w);this.K(this.confirmButton,"click",this.A)},P8=function(a){g.vL.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.T=this.o=null;this.P=[this.u];this.w=this.u;this.F=new g.JC(64);this.R=0;this.I=-1;this.C=null;if(!g.az(this.player.M())){a=this.player;var b=g.dC(a);b&&(b=b.Yl())&&(b=new N8(a,b),g.B(this,b));b=new M8(a);g.B(this,b);g.iL(a,b.element,4);this.C=new O8;g.B(this,this.C);g.iL(a,this.C.element,4);this.L=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},zya=function(a,b,c){a.F=
c;
a.player.S("presentingplayerstatechange",new g.bH(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.P(a.player.M().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.L||!a.C);if(c?0:g.jz(a.player.M())||"WEB_EMBEDDED_PLAYER"==a.player.M().deviceParams.c)g.PK(a.player).eb()?a.player.pauseVideo():(a.G=(0,g.x)(a.ON,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.ac(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=
c.videoId;if(!d&&!e||(2==a.player.getAppState()||1==a.player.getAppState())&&g.P(a.player.M().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Af,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=Wva(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Kk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().he(),(c=k6(c,b.key))&&A8(c,1))}},Hwa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},Bya={},ewa={WP:"atp",FS:"ska",tS:"que",MR:"mus",ES:"sus",YQ:"dsp",BS:"seq"},r6,n6="",wwa=swa("loadCastFramework")||swa("loadCastApplicationFramework"),Rxa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(u6,g.A);g.h=u6.prototype;g.h.hF=function(a){this.A=arguments;this.o=!1;this.Ga?this.w=(0,g.G)()+this.Ad:this.Ga=g.Vf(this.B,this.Ad)};
g.h.stop=function(){this.Ga&&(g.v.clearTimeout(this.Ga),this.Ga=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Gb.X.call(this)};
g.h.iF=function(){this.w?(this.Ga=g.Vf(this.B,this.w-(0,g.G)()),this.w=null):(this.Ga=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Ta(v6,g.A);g.h=v6.prototype;g.h.Cj=!1;g.h.wl=0;g.h.Ga=null;g.h.vx=function(a){this.o=arguments;this.Ga||this.wl?this.Cj=!0:w6(this)};
g.h.stop=function(){this.Ga&&(g.v.clearTimeout(this.Ga),this.Ga=null,this.Cj=!1,this.o=[])};
g.h.pause=function(){this.wl++};
g.h.resume=function(){this.wl--;this.wl||!this.Cj||this.Ga||(this.Cj=!1,w6(this))};
g.h.X=function(){v6.Gb.X.call(this);this.stop()};
g.h.jF=function(){this.Ga=null;this.Cj&&!this.wl&&(this.Cj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Awa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ta(zwa,z6);S8=new zwa;g.h=A6.prototype;g.h.vi=null;g.h.df=!1;g.h.Gk=null;g.h.Pu=null;g.h.tk=null;g.h.Dj=null;g.h.Wg=null;g.h.Lh=null;g.h.Vi=null;g.h.Mc=null;g.h.Om=0;g.h.kf=null;g.h.gq=null;g.h.mh=null;g.h.yl=-1;g.h.QB=!0;g.h.ci=!1;g.h.Qr=0;g.h.zp=null;var Fwa={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.aO=function(a){a=a.target;var b=this.zp;b&&3==R6(a)?b.vx():this.LC(a)};
g.h.LC=function(a){try{if(a==this.Mc)a:{var b=R6(this.Mc),c=this.Mc.C,d=this.Mc.getStatus();if(g.ie&&!g.Md(10)||g.ke&&!g.Ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.wh&&!T6(this.Mc))break a;this.ci||4!=b||7==c||(8==c||0>=d?this.o.bf(3):this.o.bf(2));K6(this);var e=this.Mc.getStatus();this.yl=e;var f=T6(this.Mc);(this.df=200==e)?(4==b&&G6(this),this.C?(Gwa(this,b,f),g.wh&&this.df&&3==b&&(this.A.ka(this.u,"tick",this.SN),this.u.start())):F6(this,f),this.df&&!this.ci&&(4==b?this.o.bo(this):(this.df=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mh=3,E6(13)):(this.mh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Mc&&T6(this.Mc)}finally{}};
g.h.SN=function(){var a=R6(this.Mc),b=T6(this.Mc);this.Om<b.length&&(K6(this),Gwa(this,a,b),this.df&&4!=a&&C6(this))};
g.h.tN=function(a){J6((0,g.x)(this.sN,this,a),0)};
g.h.sN=function(a){this.ci||(K6(this),F6(this,a),C6(this))};
g.h.YA=function(a){J6((0,g.x)(this.rN,this,a),0)};
g.h.rN=function(a){this.ci||(G6(this),this.df=a,this.o.bo(this),this.o.bf(4))};
g.h.cancel=function(){this.ci=!0;G6(this)};
g.h.BN=function(){this.Gk=null;var a=(0,g.G)();0<=a-this.Pu?(2!=this.Dj&&this.o.bf(3),G6(this),this.mh=2,E6(18),H6(this)):Jwa(this,this.Pu-a)};
g.h.getLastError=function(){return this.mh};g.h=Mwa.prototype;g.h.Or=null;g.h.Vd=null;g.h.Ap=!1;g.h.xx=null;g.h.Ln=null;g.h.As=null;g.h.Pr=null;g.h.ye=null;g.h.rg=-1;g.h.xl=null;g.h.Rk=null;g.h.connect=function(a){this.Pr=a;a=M6(this.o,null,this.Pr);E6(3);this.xx=(0,g.G)();var b=this.o.G;null!=b?(this.xl=b[0],(this.Rk=b[1])?(this.ye=1,Nwa(this)):(this.ye=2,O6(this))):($5(a,"MODE","init"),this.Vd=new A6(this,void 0,void 0,void 0),this.Vd.vi=this.Or,B6(this.Vd,a,!1,null,!0),this.ye=0)};
g.h.cE=function(a){if(a)this.ye=2,O6(this);else{E6(4);var b=this.o;b.yf=b.ah.rg;$6(b,9)}a&&this.bf(2)};
g.h.dr=function(a){return this.o.dr(a)};
g.h.abort=function(){this.Vd&&(this.Vd.cancel(),this.Vd=null);this.rg=-1};
g.h.wx=function(){return!1};
g.h.QA=function(a,b){this.rg=a.yl;if(0==this.ye)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.yf=this.rg;$6(c,2);return}this.xl=c[0];this.Rk=c[1]}else c=this.o,c.yf=this.rg,$6(c,2);else if(2==this.ye)if(this.Ap)E6(7),this.As=(0,g.G)();else if("11111"==b){if(E6(6),this.Ap=!0,this.Ln=(0,g.G)(),c=this.Ln-this.xx,!g.ie||g.Md(10)||500>c)this.rg=200,this.Vd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Ln=this.As=(0,g.G)(),this.Ap=!1};
g.h.bo=function(){this.rg=this.Vd.yl;if(this.Vd.df)0==this.ye?this.Rk?(this.ye=1,Nwa(this)):(this.ye=2,O6(this)):2==this.ye&&((!g.ie||g.Md(10)?!this.Ap:200>this.As-this.Ln)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.ye?E6(9):2==this.ye&&E6(10);var a=this.o;this.Vd.getLastError();a.yf=this.rg;$6(a,2)}};
g.h.Em=function(){return this.o.Em()};
g.h.isActive=function(){return this.o.isActive()};
g.h.bf=function(a){this.o.bf(a)};g.Ta(P6,g.hf);var Swa=/^https?$/i,Cya=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.A="";this.C=0;this.ha=b;this.V=!1;this.w=!0;this.o=this.T?Bwa(this.T):Bwa(S8);this.R=this.T?this.T.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.MA,this);try{b6(S6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));Rwa(this,f);return}a=c||
"";var e=this.headers.clone();d&&awa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.te(),Pwa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(Cya,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.da&&(this.o.responseType=this.da);"withCredentials"in this.o&&this.o.withCredentials!==this.ca&&(this.o.withCredentials=this.ca);try{Uwa(this),0<this.F&&(this.L=Owa(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.L)),this.L?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.yx,this)):this.P=g.Vf(this.yx,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),Rwa(this,f)}};
g.h.yx=function(){"undefined"!=typeof g.I1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Gb.X.call(this)};
g.h.MA=function(){this.ea()||(this.Z||this.G||this.B?Twa(this):this.vM())};
g.h.vM=function(){Twa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.kl=null;g.h.Pd=null;g.h.jc=null;g.h.Nr=null;g.h.On=null;g.h.Uv=null;g.h.ao=null;g.h.hm=0;g.h.KJ=0;g.h.wd=null;g.h.fh=null;g.h.cg=null;g.h.ji=null;g.h.ah=null;g.h.eq=null;g.h.Qj=-1;g.h.ey=-1;g.h.yf=-1;g.h.vj=0;g.h.nj=0;g.h.di=8;var a7=new g.hf;g.Ta(Wwa,g.Ke);g.Ta(Xwa,g.Ke);g.Ta(Ywa,g.Ke);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Nr=b;this.kl=c||{};d&&void 0!==e&&(this.kl.OSID=d,this.kl.OAID=e);this.C?(J6((0,g.x)(this.ow,this,a),100),bxa(this)):this.ow(a)};
g.h.ow=function(a){this.ah=new Mwa(this);this.ah.Or=null;this.ah.u=this.B;this.ah.connect(a)};
g.h.wx=function(){return 0==this.o};
g.h.XA=function(a){this.fh=null;exa(this,a)};
g.h.WA=function(){this.cg=null;this.jc=new A6(this,this.w,"rpc",this.F);this.jc.vi=null;this.jc.Qr=0;var a=this.Uv.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.eq?"0":"1");Y5(a,"AID",this.Qj);V6(this,a);if(!g.ie||g.Md(10))Y5(a,"TYPE","xmlhttp"),B6(this.jc,a,!0,this.ao,!1);else{Y5(a,"TYPE","html");var b=this.jc,c=!!this.ao;b.Dj=3;b.Wg=Z5(a.clone());Iwa(b,c)}};
g.h.QA=function(a,b){if(0!=this.o&&(this.jc==a||this.Pd==a))if(this.yf=a.yl,this.Pd==a&&3==this.o)if(7<this.di){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.cg){if(this.jc)if(this.jc.tk+3E3<this.Pd.tk)X6(this),this.jc.cancel(),this.jc=null;else break a;Z6(this);E6(19)}}else this.ey=c[1],0<this.ey-this.Qj&&37500>c[2]&&this.eq&&0==this.nj&&!this.ji&&(this.ji=J6((0,g.x)(this.mK,this),6E3));else $6(this,11)}else b!=Bya.tQ.o&&$6(this,11);else if(this.jc==
a&&X6(this),!g.fc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Qj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.ao=e[2],e=e[3],null!=e?this.di=e:this.di=6,this.o=3,this.wd&&this.wd.kw(),this.Uv=M6(this,this.Em()?this.ao:null,this.Nr),fxa(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.wd&&this.wd.jw(e),this.nj=0)}}};
g.h.mK=function(){null!=this.ji&&(this.ji=null,this.jc.cancel(),this.jc=null,Z6(this),E6(20))};
g.h.bo=function(a){if(this.jc==a){X6(this);this.jc=null;var b=2}else if(this.Pd==a)this.Pd=null,b=1;else return;this.yf=a.yl;if(0!=this.o)if(a.df)1==b?(b=(0,g.G)()-a.tk,a7.dispatchEvent(new Xwa(a7,a.Vi?a.Vi.length:0,b,this.vj)),W6(this),this.A.length=0):fxa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.yf)){if(d=1==b)this.Pd||this.fh||1==this.o||2<=this.vj?d=!1:(this.fh=J6((0,g.x)(this.XA,this,a),gxa(this,this.vj)),this.vj++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.BE=function(a){if(!g.ab(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.LO=function(a){a?E6(2):(E6(1),hxa(this,8))};
g.h.dr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.ca=!1;return a};
g.h.isActive=function(){return!!this.wd&&this.wd.isActive(this)};
g.h.bf=function(a){a7.dispatchEvent(new Ywa(a7,a))};
g.h.Em=function(){return!(!g.ie||g.Md(10))};
g.h=ixa.prototype;g.h.kw=function(){};
g.h.jw=function(){};
g.h.iw=function(){};
g.h.Tq=function(){};
g.h.Sw=function(){return{}};
g.h.isActive=function(){return!0};g.h=jxa.prototype;g.h.isEmpty=function(){return g.bb(this.o)&&g.bb(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.ab(this.o,a)||g.ab(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Vqa)(b,a);0<=c?(g.db(b,c),b=!0):b=!1;return b||g.eb(this.u,a)};
g.h.Fd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(b7,g.A);g.h=b7.prototype;g.h.lN=function(){this.Ad=Math.min(3E5,2*this.Ad);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Ad+15E3*Math.random();this.o.Ua(a);this.u=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ad=5E3};g.Ta(c7,ixa);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.Dh=function(a){return this.w.wi(a)};
g.h.S=function(a,b){return this.w.S.apply(this.w,arguments)};
g.h.dispose=function(){this.ub||(this.ub=!0,g.Ie(this.w),mxa(this),g.Ie(this.u),this.u=null)};
g.h.ea=function(){return this.ub};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.I="";this.u.stop();this.B=a||null;this.A=b||0;a=this.P+"/test";b=this.P+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.wd=null);d.wd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Qj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Tb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&cxa(this.o,c)};
g.h.kw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)cxa(this.o,a[b])}this.S("handlerOpened")};
g.h.iw=function(a){var b=2==a&&401==this.o.yf;4==a||b||this.u.start();this.S("handlerError",a)};
g.h.Tq=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Sw=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.Tb(a,this.B);return a};
g.h.jw=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),axa(this.o)):this.S("handlerMessage",new kxa(a[0],a[1]))};
g.h.oO=function(){this.u.isActive();var a=this.o,b=0;a.jc&&b++;a.Pd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var uxa=(0,g.G)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ta(m7,g.O);m7.prototype.he=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.O);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ga)&&this.PC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ga)||(g.Jo(this.Ga),this.Ga=NaN)};
g.h.X=function(){this.stop();g.O.prototype.X.call(this)};
g.h.PC=function(){this.Ga=NaN;this.o=g.Eq(f7(this.C,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.rP,this),onError:(0,g.x)(this.qP,this),Ud:(0,g.x)(this.sP,this)})};
g.h.rP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.S("pairingComplete",new e6(c))};
g.h.qP=function(a){this.o=null;a.status&&404==a.status?this.u>=Dya.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=Dya[this.u],this.Ga=g.Ho((0,g.x)(this.PC,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.h.sP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var Dya=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.S("screenChange");!g.Es("yt-remote-lounge-token-expiration")&&yxa(this);g.Jo(this.u);this.u=g.Ho((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);vxa(this,a);q7(this,!1);this.S("screenChange");b(a);a.token||yxa(this)};
g.h.remove=function(a,b){var c=o7(this);xxa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.h.bq=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.h.X=function(){g.Jo(this.u);p7.Gb.X.call(this)};
g.h.tF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.sF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.O);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Es("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?u7(this):(this.A=(0,g.G)()+3E5,g.Ds("yt-remote-fast-check-period",this.A),this.gu())};
g.h.isEmpty=function(){return g.Nb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Bb(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.Jo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.O.prototype.X.call(this)};
g.h.gu=function(){g.Jo(this.w);this.w=NaN;this.u&&this.u.abort();var a=Bxa(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Hb(a).join(",")},(0,g.x)(this.UM,this,a),(0,g.x)(this.TM,this))}else t7(this,{}),u7(this)};
g.h.UM=function(a,b){this.u=null;var c=g.Hb(Bxa(this));if(g.tb(c,g.Hb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Ub("Changing Screen set during request."),this.gu()};
g.h.TM=function(a){this.Ub("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Ub=function(a){i7("OnlineScreenService",a)};g.Ta(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.S("screenChange"),this.u.isEmpty()||this.S("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.bq=function(a,b,c,d){this.w.contains(a)?this.w.bq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.he=function(a){return a?this.o:g.gb(this.o,(0,g.ve)(this.A,function(b){return!this.contains(b)},this))};
g.h.QC=function(){return(0,g.ve)(this.he(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.RC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ie(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ie(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.uP=function(a,b,c,d){g.Eq(f7(this.C,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||Fxa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Fxa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Ud:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.Ie(this.w);g.Ie(this.u);v7.Gb.X.call(this)};
g.h.CF=function(){Gxa(this);this.S("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ta(y7,g.O);g.h=y7.prototype;g.h.pp=function(a){this.w=a;this.S("sessionScreen",this.w)};
g.h.le=function(a){this.ea()||(a&&z7(this,""+a),this.w=null,this.S("sessionScreen",null))};
g.h.info=function(a){i7(this.R,a)};
g.h.TC=function(){return null};
g.h.pu=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.pu("");y7.Gb.X.call(this)};g.Ta(A7,y7);g.h=A7.prototype;g.h.ou=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Ixa(this)};
g.h.Rj=function(a){this.info("launchWithParams no-op for Cast: "+g.Kk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.le()},this),(0,g.x)(function(){this.le(Error("Failed to stop receiver app."))},this)):this.le(Error("Stopping cast device witout session."))};
g.h.pu=g.Ia;g.h.X=function(){this.info("disposeInternal");g.Jo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Gb.X.call(this)};
g.h.JN=function(a,b){if(!this.ea())if(b){var c=x6(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kk(c));switch(d){case "mdxSessionStatus":Hxa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.mx=function(a,b,c,d){Exa(this.I,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ho((0,g.x)(this.mx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.TC=function(){return this.o};
g.h.vP=function(a){this.ea()||a||(z7(this,"Cast session died."),this.le())};g.Ta(B7,y7);g.h=B7.prototype;g.h.ou=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.Rj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ia;g.Jo(this.C);this.A?this.A.stop((0,g.x)(this.le,this,null),(0,g.x)(this.le,this,"Failed to stop DIAL device.")):this.le()};
g.h.X=function(){this.o();this.o=g.Ia;g.Jo(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;B7.Gb.X.call(this)};
g.h.yP=function(a){this.ea()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ia,this.le())};
g.h.Zr=function(a){this.P=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Kxa(this));a(b);Jxa(this)}else this.F=(0,g.x)(function(){g.Jo(this.C);this.F=g.Ia;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Kxa(this));a(c);Jxa(this)},this),this.C=g.Ho((0,g.x)(function(){this.F()},this),100)};
g.h.VF=function(a,b,c){Exa(this.I,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.pp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Zr(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Zr(b,c)},this))};g.Ta(C7,y7);C7.prototype.stop=function(){this.le()};
C7.prototype.ou=g.Ia;C7.prototype.Rj=function(){g.Jo(this.o);this.o=NaN;var a=k6(this.I.he(),this.u.label);a?this.pp(a):this.le(Error("No such screen"))};
C7.prototype.X=function(){g.Jo(this.o);this.o=NaN;C7.Gb.X.call(this)};g.Ta(D7,g.O);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.AM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.TA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.KK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.A),rxa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.SC,this)),this.w=Mxa(this),chrome.cast.setCustomReceivers(this.w,g.Ia,(0,g.x)(function(k){this.Ub("Failed to set initial custom receivers: "+g.Kk(k))},this)),this.S("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Ub("Failed to initialize API: "+g.Kk(k));
b(!1)},this))};
g.h.vO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.he(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Lxa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ia,(0,g.x)(function(e){this.Ub("Failed to set initial custom receivers: "+g.Kk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.pu(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.wO=function(a){this.ea()?this.Ub("Setting connection data on disposed cast v2"):this.o?this.o.Rj(a):this.Ub("Setting connection data without a session")};
g.h.xP=function(){this.ea()?this.Ub("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.TA,this),(0,g.x)(this.YM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.SC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=oxa,b=g.w("yt.mdx.remote.debug.handlers_");g.eb(b||[],a);g.Ie(this.o);D7.Gb.X.call(this)};
g.h.Ub=function(a){i7("Controller",a)};
g.h.VA=function(a,b){this.o==a&&(b||G7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.h.wM=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.S("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Ub("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Ub("Stopping receiver w/o session: "+a.friendlyName)}else this.Ub("onReceiverAction_ called without receiver.")};
g.h.KK=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ub("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Ub("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ub('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.VF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Zr,b))};
g.h.TA=function(a){if(!this.ea()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Ub("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.he(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ie(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.VA,this,this.o)),this.o.Rj(null));this.o.ou(a)}}};
g.h.wP=function(){return this.o?this.o.TC():null};
g.h.YM=function(a){this.ea()||(this.Ub("Failed to estabilish a session: "+g.Kk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.AM=function(a){E7("Receiver availability updated: "+a);if(!this.ea()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.S("yt-remote-cast2-availability-change",F7(this))}};
g.h.SC=function(){this.ea()||(this.w=Mxa(this),E7("Updating custom receivers: "+g.Kk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ia,(0,g.x)(function(){this.Ub("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.wO;D7.prototype.setConnectedScreenStatus=D7.prototype.vO;D7.prototype.stopSession=D7.prototype.xP;D7.prototype.getCastSession=D7.prototype.wP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.h=R7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.P=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.w=!isNaN(this.A))};
g.h.eb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.w?this.G+T7(this):this.G};
g.h.clone=function(){return new R7(X7(this))};g.r(Z7,g.O);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ia,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ia,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.eb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ia,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.S("remotePlayerChange")}else a8(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ia,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.S("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Ub("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Ub("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Ra(this.setVolume,a,b))};
g.h.VB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kk(b.style),g.Tb(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Ra(this.VB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.OC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Ra(this.OC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Ra(this.nextVideo,a,b))};
g.h.Aw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Aw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.O.prototype.dispose.call(this)};
g.h.X=function(){Zxa(this);this.A=null;this.B.clear();Y7(this,null);g.O.prototype.X.call(this)};
g.h.Su=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.bb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.tM=function(a,b){this.S(a,b)};
g.h.sK=function(a){if(!a)this.jm(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.jm=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),$xa(this),this.S("remotePlayerChange")};
g.h.rK=function(a){a?($xa(this),this.S("remotePlayerChange")):this.jm(null)};
g.h.DK=function(){var a=Wxa();a&&Y7(this,a)};
g.h.Ub=function(a){i7("CP",a)};g.r(f8,g.O);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Va.listId=c);this.Va.videoId=d;this.Va.index=k||0;this.Va.state=3;U7(this.Va,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Kk(l));this.o.connect({method:"setPlaylist",
params:g.Kk(l)},a,mwa())}else g8("Connecting without params"),this.o.connect({},a,mwa());bya(this)};
g.h.dispose=function(){this.ea()||(this.S("beforeDispose"),h8(this,3));g.O.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.Jo(this.F);this.F=NaN;g.Jo(this.G);this.G=NaN;this.w=null;g.Fp(this.R);this.R.length=0;this.o.dispose();g.O.prototype.X.call(this);this.A=this.C=this.u=this.Va=this.o=null};
g.h.lF=function(){this.tj(2)};
g.h.wK=function(){g8("Channel opened");this.L&&(this.L=!1,j8(this),this.P=g.Ho((0,g.x)(function(){g8("Timing out waiting for a screen.");this.tj(1)},this),15E3));
qwa(lxa(this.o),this.T)};
g.h.tK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.uK=function(a){q6();isNaN(this.sl())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.L=!0,g8("Channel error: "+a+" with reconnection in "+this.sl()+" ms"),h8(this,2))};
g.h.vK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Kk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Dc)(a,function(c){return new d6(c)});
a=!!g.Ya(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
eya(this,a);break;case "loungeScreenDisconnected":g.fb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
eya(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.Ya(this.u,function(c){return b?c.id==b.id:!1})||Xva(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.fb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":gya(this,a);break;case "nowPlaying":iya(this,a);break;case "onStateChange":hya(this,a);break;case "onAdStateChange":jya(this,a);break;case "onVolumeChanged":kya(this,a);break;case "onSubtitlesTrackChanged":fya(this,a);break;case "nowAutoplaying":lya(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.S("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.S("autoplayModeChange",this.A);"DISABLED"==this.A&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":mya(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.kO=function(){if(this.w){var a=this.w;this.w=null;this.Va.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.bF=function(){var a=3;this.ea()||(a=0,isNaN(this.sl())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.tj=function(a){g8("Disconnecting with "+a);i8(this);this.S("beforeDisconnect",a);1==a&&q6();mxa(this.o,a);this.dispose()};
g.h.aF=function(){var a=this.Va;this.w&&(a=this.Va.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.xO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Va.videoId&&(this.w=b.videoId,g.Jo(this.F),this.F=g.Ho((0,g.x)(this.kO,this),5E3));var c=[];this.Va.listId==b.listId&&this.Va.videoId==b.videoId&&this.Va.index==b.index||c.push("remoteQueueChange");this.Va.playerState==b.playerState&&this.Va.volume==b.volume&&this.Va.muted==b.muted&&V7(this.Va)==V7(b)&&g.Kk(this.Va.o)==g.Kk(b.o)||c.push("remotePlayerChange");this.Va.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.h.kx=function(){var a=this.o.C.id,b=g.Ya(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.sl=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.G)():NaN};
g.h.PE=function(){return this.A||"UNSUPPORTED"};
g.h.QE=function(){return this.C||""};
g.h.pP=function(){if(!isNaN(this.sl())){var a=this.o.u;g.vn(a.o);a.start()}};
g.h.sO=function(a,b){l8(this,a,b);dya(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Dh;f8.prototype.getProxyState=f8.prototype.bF;f8.prototype.disconnect=f8.prototype.tj;f8.prototype.getPlayerContextData=f8.prototype.aF;f8.prototype.setPlayerContextData=f8.prototype.xO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.kx;f8.prototype.getReconnectTimeout=f8.prototype.sl;f8.prototype.getAutoplayMode=f8.prototype.PE;f8.prototype.getAutoplayVideoId=f8.prototype.QE;f8.prototype.reconnect=f8.prototype.pP;
f8.prototype.sendMessage=f8.prototype.sO;g.r(m8,m7);g.h=m8.prototype;g.h.he=function(a){return this.zd.$_gs(a)};
g.h.contains=function(a){return!!this.zd.$_c(a)};
g.h.get=function(a){return this.zd.$_g(a)};
g.h.start=function(){this.zd.$_st()};
g.h.add=function(a,b,c){this.zd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.zd.$_r(a,b,c)};
g.h.bq=function(a,b,c,d){this.zd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.zd.$_ubk(this.u[a]);this.u.length=0;this.zd=null;m7.prototype.X.call(this)};
g.h.tP=function(){this.S("screenChange")};
g.h.UL=function(){this.S("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.uP;v7.prototype.$_gsppc=v7.prototype.RC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.bq;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.he;v7.prototype.$_gos=v7.prototype.QC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Dh;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.X=function(){g.A.prototype.X.call(this);this.A.stop();this.C.stop();this.L.stop();this.V();this.o.unsubscribe("proxyStateChange",this.PA,this);this.o.unsubscribe("remotePlayerChange",this.om,this);this.o.unsubscribe("remoteQueueChange",this.qp,this);this.o.unsubscribe("autoplayUpNext",this.dA,this);this.o.unsubscribe("previousNextChange",this.KA,this);this.o.unsubscribe("nowAutoplaying",this.FA,this);this.o.unsubscribe("autoplayDismissed",this.cA,this);this.o=this.B=null};
g.h.kz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":$7(this.o).eb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.P.vx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.qK=function(a){this.L.hF(a)};
g.h.UO=function(a){this.kz("control_subtitles_set_track",g.Nb(a)?null:a)};
g.h.eC=function(){var a=this.u.getOption("captions","track");g.Nb(a)||K8(this,a)};
g.h.tA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.om,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.om,this)}};
g.h.qL=function(){g.Nb(this.F)||yya(this,this.F);this.G=!1};
g.h.PA=function(a,b){this.C.stop();2==b&&this.dC()};
g.h.om=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.I=1;break;case 1082:case 1083:this.B.I=0;break;default:this.B.I=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.JC(8));this.cC();break;case 1085:case 3:I8(this,new g.JC(9));break;case 1083:case 0:I8(this,new g.JC(2));this.P.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.JC(4));break;case 2:I8(this,new g.JC(4));H8(this,V7(a));
break;case -1:I8(this,new g.JC(64));break;case -1E3:I8(this,new g.JC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,yya(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.R.isActive()||this.DC()}else xya(this)};
g.h.KA=function(){this.u.S("mdxpreviousnextchange")};
g.h.qp=function(){J8(this)||xya(this)};
g.h.bE=function(){this.o.Aw()};
g.h.dA=function(){};
g.h.FA=function(a){isNaN(a)||this.u.S("mdxnowautoplaying",a)};
g.h.cA=function(){this.u.S("mdxautoplaycanceled")};
g.h.yI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.DC=function(){if(J8(this)){var a=$7(this.o);this.w.bb(this.T);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.T=this.w.K(this.u,"onVolumeChange",this.tA)}};
g.h.cC=function(){this.A.stop();if(!this.o.ea()){var a=$7(this.o);a.eb()&&I8(this,new g.JC(8));H8(this,V7(a));this.A.start()}};
g.h.dC=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.R);M8.prototype.A=function(a){Aya(this,a.state)};g.r(N8,g.iO);N8.prototype.L=function(){var a=this.A.getOption("remote","receivers");a&&1<a.length&&!this.A.getOption("remote","quickCast")?(this.G=g.vb(a,this.B,this),g.kO(this,(0,g.Dc)(a,this.B)),a=this.A.getOption("remote","currentReceiver"),this.Db(this.B(a)),this.enable(!0)):this.enable(!1)};
N8.prototype.B=function(a){return a.key};
N8.prototype.Ze=function(a){return"cast-selector-receiver"==a?"Cast...":this.G[a].name};
N8.prototype.hd=function(a){g.iO.prototype.hd.call(this,a);this.A.setOption("remote","currentReceiver",this.G[a]);this.u.gb()};g.r(O8,g.R);O8.prototype.ac=function(){this.u.show()};
O8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
O8.prototype.A=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(P8,g.vL);g.h=P8.prototype;
g.h.create=function(){rya(g.Ry(this.player.M()));this.A.push(g.Oo("yt-remote-before-disconnect",this.nK,this));this.A.push(g.Oo("yt-remote-connection-change",this.BM,this));this.A.push(g.Oo("yt-remote-receiver-availability-change",this.NA,this));this.A.push(g.Oo("yt-remote-auto-connect",this.zM,this));this.A.push(g.Oo("yt-remote-receiver-resumed",this.yM,this));this.A.push(g.Oo("mdx-privacy-popup-confirm",this.WN,this));this.A.push(g.Oo("mdx-privacy-popup-cancel",this.VN,this));this.NA()};
g.h.load=function(){this.player.cancelPlayback();g.vL.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=wya())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.R=a||0,this.player.S("progresssync",a,void 0));zya(this,this.F,this.F);g.bT(this.player.app,6)};
g.h.unload=function(){this.player.S("mdxautoplaycanceled");this.w=this.u;g.Je(this.B,this.o);this.o=this.B=null;g.vL.prototype.unload.call(this);g.bT(this.player.app,5);Q8(this)};
g.h.X=function(){g.Po(this.A);g.vL.prototype.X.call(this)};
g.h.Rl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.kz.apply(this.B,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.I};
g.h.dF=function(){return this.loaded?this.B.suggestion:null};
g.h.By=function(){return this.o?$7(this.o).P:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.R};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.M().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Rc():!a.isAdPlaying()&&this.player.Rc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+T7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.yG=function(){this.o&&this.o.OC()};
g.h.nK=function(a){1==a&&(this.T=this.o?$7(this.o):null)};
g.h.BM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.T=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.Ie(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.T)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.NA=function(){this.P=[this.u].concat(tya());var a=y8()||this.u;R8(this,a);this.player.na("onMdxReceiversChange")};
g.h.ON=function(a){!this.L&&g.dH(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.zM=function(){var a=y8();R8(this,a)};
g.h.yM=function(){this.w=y8()};
g.h.WN=function(){this.L=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.VN=function(){this.L=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Pc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.P;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.P.length&&"cast-selector-receiver"==this.P[1].key?(b&&P7(),!0):!1}};
g.h.zG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.KL.remote=P8;})(_yt_player);
